-- Load 232 Acquisition Markets for Catalyst Capital Partners
-- PRODUCTION READY - Run this in your Production database

-- Alabama Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Birmingham, AL MSA', 'Blount', 'AL', 'Blount County, AL', NULL, ARRAY['Active Adult'], true, 33.9773580, -86.5664400);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Birmingham, AL MSA', 'Jefferson', 'AL', 'Jefferson County, AL', '(Birmingham)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 33.5534440, -86.8965360);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Birmingham, AL MSA', 'Shelby', 'AL', 'Shelby County, AL', '(Birmingham)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 33.2668930, -86.6610070);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Birmingham, AL MSA', 'St. Clair', 'AL', 'St. Clair County, AL', NULL, ARRAY['Active Adult'], true, 33.7194910, -86.3113270);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Huntsville, AL MSA', 'Limestone', 'AL', 'Limestone County, AL', NULL, ARRAY['Active Adult'], true, 34.8102390, -86.9814000);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Huntsville, AL MSA', 'Madison', 'AL', 'Madison County, AL', '(Huntsville)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 34.7642380, -86.5510800);

-- Arizona Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Phoenix MSA', 'Maricopa', 'AZ', 'Maricopa County, AZ', NULL, ARRAY['Active Adult'], true, 33.3451760, -112.4989300);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Phoenix MSA', 'Pinal', 'AZ', 'Pinal County, AZ', NULL, ARRAY['Active Adult'], true, 32.9185210, -111.3663390);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Tucson, AZ MSA', 'Pima', 'AZ', 'Pima County', NULL, ARRAY['Active Adult'], true, 32.1280380, -111.7836570);

-- California Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Fresno, CA MSA', 'Fresno', 'CA', 'Fresno County', NULL, ARRAY['Active Adult'], true, 36.7610060, -119.6550190);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Fresno, CA MSA', 'Madera', 'CA', 'Madera County', NULL, ARRAY['Active Adult'], true, 37.2098210, -119.7498020);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Los Angeles MSA', 'Los Angeles', 'CA', 'Los Angeles County, CA', NULL, ARRAY['Active Adult'], true, 34.1963980, -118.2618620);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Los Angeles MSA', 'Orange', 'CA', 'Orange County, CA', NULL, ARRAY['Active Adult'], true, 33.6756870, -117.7772070);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Sacramento, CA MSA', 'El Dorado', 'CA', 'El Dorado County', NULL, ARRAY['Active Adult'], true, 38.7856120, -120.5342250);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Sacramento, CA MSA', 'Placer', 'CA', 'Placer County', NULL, ARRAY['Active Adult'], true, 39.0620320, -120.7227180);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Sacramento, CA MSA', 'Sacramento', 'CA', 'Sacramento County', NULL, ARRAY['Active Adult'], true, 38.4501360, -121.3443290);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Sacramento, CA MSA', 'Yolo', 'CA', 'Yolo County', NULL, ARRAY['Active Adult'], true, 38.6796090, -121.9027500);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('San Diego MSA', 'San Diego', 'CA', 'San Diego County, CA', NULL, ARRAY['Active Adult'], true, 33.0236040, -116.7761170);

-- Colorado Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Denver MSA', 'Adams', 'CO', 'Adams County, CO', NULL, ARRAY['Active Adult'], true, 39.8743250, -104.3318720);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Denver MSA', 'Arapahoe', 'CO', 'Arapahoe County, CO', NULL, ARRAY['Active Adult'], true, 39.6445540, -104.3317070);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Denver MSA', 'Denver', 'CO', 'Denver County, CO', NULL, ARRAY['Active Adult'], true, 39.7618500, -104.8811050);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Denver MSA', 'Douglas', 'CO', 'Douglas County, CO', NULL, ARRAY['Active Adult'], true, 39.3254140, -104.9259870);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Denver MSA', 'Jefferson', 'CO', 'Jefferson County, CO', NULL, ARRAY['Active Adult'], true, 39.5795110, -105.2454620);

-- Connecticut Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Hartford, CT MSA', 'Hartford', 'CT', 'Hartford County', NULL, ARRAY['Active Adult'], true, 41.7821870, -72.7008060);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Hartford, CT MSA', 'Middlesex', 'CT', 'Middlesex County', NULL, ARRAY['Active Adult'], true, 37.6054910, -76.4381710);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Hartford, CT MSA', 'Tolland', 'CT', 'Tolland County', NULL, ARRAY['Active Adult'], true, 41.8825530, -72.3610390);

-- Washington DC
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Washington, D.C. MSA', 'District of Columbia', 'DC', 'District of Columbia', NULL, ARRAY['Active Adult'], true, 38.9042470, -77.0165170);

-- Florida Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Jacksonville, FL MSA', 'Baker', 'FL', 'Baker County', NULL, ARRAY['Active Adult'], true, 30.3244420, -82.3022840);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Jacksonville, FL MSA', 'Clay', 'FL', 'Clay County', NULL, ARRAY['Active Adult'], true, 29.9865840, -81.8650360);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Jacksonville, FL MSA', 'Duval', 'FL', 'Duval County', NULL, ARRAY['Active Adult'], true, 30.3352450, -81.6481130);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Jacksonville, FL MSA', 'Nassau', 'FL', 'Nassau County', NULL, ARRAY['Active Adult'], true, 30.6059630, -81.7650870);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Jacksonville, FL MSA', 'St. Johns', 'FL', 'St. Johns County', NULL, ARRAY['Active Adult'], true, 29.8904880, -81.4000400);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Miami MSA', 'Broward', 'FL', 'Broward County, FL', NULL, ARRAY['Active Adult'], true, 26.1935350, -80.4766830);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Miami MSA', 'Miami-Dade', 'FL', 'Miami-Dade County, FL', NULL, ARRAY['Active Adult'], true, 25.6160090, -80.5037500);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Miami MSA', 'Palm Beach', 'FL', 'Palm Beach County, FL', NULL, ARRAY['Active Adult'], true, 26.6491260, -80.4483540);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Orlando MSA', 'Lake', 'FL', 'Lake County, FL', NULL, ARRAY['Active Adult'], true, 28.7641130, -81.7122820);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Orlando MSA', 'Orange', 'FL', 'Orange County, FL', NULL, ARRAY['Active Adult'], true, 28.5143910, -81.3232840);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Orlando MSA', 'Osceola', 'FL', 'Osceola County, FL', NULL, ARRAY['Active Adult'], true, 28.0590270, -81.1393120);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Orlando MSA', 'Seminole', 'FL', 'Seminole County, FL', NULL, ARRAY['Active Adult'], true, 28.6900650, -81.1319750);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Tampa MSA', 'Hernando', 'FL', 'Hernando County, FL', NULL, ARRAY['Active Adult'], true, 28.5559950, -82.5259690);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Tampa MSA', 'Hillsborough', 'FL', 'Hillsborough County, FL', NULL, ARRAY['Active Adult'], true, 27.8931540, -82.3799910);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Tampa MSA', 'Pasco', 'FL', 'Pasco County, FL', NULL, ARRAY['Active Adult'], true, 28.3098230, -82.5110060);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Tampa MSA', 'Pinellas', 'FL', 'Pinellas County, FL', NULL, ARRAY['Active Adult'], true, 27.8921190, -82.7373330);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Tampa MSA', 'Polk', 'FL', 'Polk County, FL', NULL, ARRAY['Active Adult'], true, 28.0227320, -81.7829780);

-- Georgia Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Atlanta MSA', 'Barrow', 'GA', 'Barrow County, GA', NULL, ARRAY['Active Adult'], true, 33.9990910, -83.7144800);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Atlanta MSA', 'Cherokee', 'GA', 'Cherokee County, GA', NULL, ARRAY['Active Adult'], true, 34.2355810, -84.4768180);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Atlanta MSA', 'Clayton', 'GA', 'Clayton County, GA', NULL, ARRAY['Active Adult'], true, 33.5379670, -84.3662210);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Atlanta MSA', 'Cobb', 'GA', 'Cobb County, GA', NULL, ARRAY['Active Adult'], true, 33.9377930, -84.5815060);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Atlanta MSA', 'DeKalb', 'GA', 'DeKalb County, GA', NULL, ARRAY['Active Adult'], true, 33.7675370, -84.2232680);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Atlanta MSA', 'Douglas', 'GA', 'Douglas County, GA', NULL, ARRAY['Active Adult'], true, 33.6896030, -84.7617980);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Atlanta MSA', 'Forsyth', 'GA', 'Forsyth County, GA', NULL, ARRAY['Active Adult'], true, 34.2242760, -84.1299110);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Atlanta MSA', 'Fulton', 'GA', 'Fulton County, GA', '(Atlanta)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 33.7862320, -84.5512820);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Atlanta MSA', 'Gwinnett', 'GA', 'Gwinnett County, GA', NULL, ARRAY['Active Adult'], true, 33.9565180, -84.0048650);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Atlanta MSA', 'Hall', 'GA', 'Hall County, GA', NULL, ARRAY['Active Adult'], true, 34.3133460, -83.8327900);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Atlanta MSA', 'Henry', 'GA', 'Henry County, GA', NULL, ARRAY['Active Adult'], true, 33.4587130, -84.1405450);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Atlanta MSA', 'Paulding', 'GA', 'Paulding County, GA', NULL, ARRAY['Active Adult'], true, 33.9196910, -84.8823760);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Atlanta MSA', 'Rockdale', 'GA', 'Rockdale County, GA', NULL, ARRAY['Active Adult'], true, 33.6534800, -84.0298020);

-- Idaho Markets  
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boise, ID MSA', 'Ada', 'ID', 'Ada County, ID', '(Boise)', ARRAY['Active Adult', 'BTR'], true, 43.4585350, -116.2412570);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boise, ID MSA', 'Canyon', 'ID', 'Canyon County, ID', NULL, ARRAY['Active Adult'], true, 43.6632470, -116.6990090);

-- Illinois Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Chicago MSA', 'Cook', 'IL', 'Cook County, IL', '(Chicago)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 41.7409910, -87.7278680);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Chicago MSA', 'DuPage', 'IL', 'DuPage County, IL', NULL, ARRAY['Active Adult'], true, 41.8539610, -88.0823770);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Chicago MSA', 'Kane', 'IL', 'Kane County, IL', NULL, ARRAY['Active Adult'], true, 41.9364150, -88.4392910);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Chicago MSA', 'Lake', 'IL', 'Lake County, IL', NULL, ARRAY['Active Adult'], true, 42.3316780, -87.8880900);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Chicago MSA', 'McHenry', 'IL', 'McHenry County, IL', NULL, ARRAY['Active Adult'], true, 42.3262960, -88.4523720);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Chicago MSA', 'Will', 'IL', 'Will County, IL', NULL, ARRAY['Active Adult'], true, 41.4659650, -88.0796590);

-- Indiana Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Indianapolis, IN MSA', 'Hamilton', 'IN', 'Hamilton County, IN', NULL, ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 40.0548600, -85.9993670);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Indianapolis, IN MSA', 'Hancock', 'IN', 'Hancock County, IN', NULL, ARRAY['Active Adult'], true, 39.8405420, -85.8131930);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Indianapolis, IN MSA', 'Hendricks', 'IN', 'Hendricks County, IN', NULL, ARRAY['Active Adult'], true, 39.7682900, -86.5373270);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Indianapolis, IN MSA', 'Johnson', 'IN', 'Johnson County, IN', NULL, ARRAY['Active Adult'], true, 39.5071220, -86.1017790);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Indianapolis, IN MSA', 'Marion', 'IN', 'Marion County, IN', '(Indianapolis)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 39.7770050, -86.1463120);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Indianapolis, IN MSA', 'Morgan', 'IN', 'Morgan County, IN', NULL, ARRAY['Active Adult'], true, 39.4878180, -86.4352330);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Indianapolis, IN MSA', 'Shelby', 'IN', 'Shelby County, IN', NULL, ARRAY['Active Adult'], true, 39.5312060, -85.7961270);

-- Kansas Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Kansas City, KS MSA', 'Johnson', 'KS', 'Johnson County, KS', NULL, ARRAY['Active Adult'], true, 38.8435370, -94.8113730);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Kansas City, KS MSA', 'Leavenworth', 'KS', 'Leavenworth County, KS', NULL, ARRAY['Active Adult'], true, 39.2929370, -94.9928890);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Kansas City, KS MSA', 'Miami', 'KS', 'Miami County, KS', NULL, ARRAY['Active Adult'], true, 38.5750610, -94.8556790);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Kansas City, KS MSA', 'Wyandotte', 'KS', 'Wyandotte County, KS', '(Kansas City)', ARRAY['Active Adult', 'BTR'], true, 39.1140070, -94.7644040);

-- Maryland Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Washington, D.C. MSA', 'Anne Arundel', 'MD', 'Anne Arundel County, MD', NULL, ARRAY['Active Adult'], true, 39.0015830, -76.5938070);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Washington, D.C. MSA', 'Charles', 'MD', 'Charles County, MD', NULL, ARRAY['Active Adult'], true, 38.4618110, -77.0043520);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Washington, D.C. MSA', 'Frederick', 'MD', 'Frederick County, MD', NULL, ARRAY['Active Adult'], true, 39.4781740, -77.4002430);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Washington, D.C. MSA', 'Howard', 'MD', 'Howard County, MD', NULL, ARRAY['Active Adult'], true, 39.2596500, -76.9458110);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Washington, D.C. MSA', 'Montgomery', 'MD', 'Montgomery County, MD', NULL, ARRAY['Active Adult'], true, 39.1365350, -77.2063110);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Washington, D.C. MSA', 'Prince George''s', 'MD', 'Prince George''s County, MD', NULL, ARRAY['Active Adult'], true, 38.8197110, -76.8635740);

-- Massachusetts Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boston MSA', 'Essex', 'MA', 'Essex County', NULL, ARRAY['Active Adult'], true, 42.6395530, -70.8547840);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boston MSA', 'Middlesex', 'MA', 'Middlesex County', NULL, ARRAY['Active Adult'], true, 42.4862550, -71.3828570);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boston MSA', 'Norfolk', 'MA', 'Norfolk County', NULL, ARRAY['Active Adult'], true, 42.1737060, -71.1881990);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boston MSA', 'Plymouth', 'MA', 'Plymouth County', NULL, ARRAY['Active Adult'], true, 41.9989520, -70.7476420);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boston MSA', 'Suffolk', 'MA', 'Suffolk County', '(Boston)', ARRAY['Active Adult', 'BTR'], true, 42.3498600, -71.0594910);

-- Michigan Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Detroit MSA', 'Livingston', 'MI', 'Livingston County', NULL, ARRAY['Active Adult'], true, 42.6054260, -83.9195420);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Detroit MSA', 'Macomb', 'MI', 'Macomb County', NULL, ARRAY['Active Adult'], true, 42.6826530, -82.9252830);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Detroit MSA', 'Oakland', 'MI', 'Oakland County', NULL, ARRAY['Active Adult'], true, 42.6610730, -83.3880110);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Detroit MSA', 'St. Clair', 'MI', 'St. Clair County', NULL, ARRAY['Active Adult'], true, 42.9118060, -82.6621930);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Detroit MSA', 'Washtenaw', 'MI', 'Washtenaw County', NULL, ARRAY['Active Adult'], true, 42.2536870, -83.8989750);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Detroit MSA', 'Wayne', 'MI', 'Wayne County', '(Detroit)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 42.2818560, -83.2363080);

-- Minnesota Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Minneapolis MSA', 'Anoka', 'MN', 'Anoka County', NULL, ARRAY['Active Adult'], true, 45.2739020, -93.2540920);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Minneapolis MSA', 'Carver', 'MN', 'Carver County', NULL, ARRAY['Active Adult'], true, 44.8234340, -93.8025510);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Minneapolis MSA', 'Dakota', 'MN', 'Dakota County', NULL, ARRAY['Active Adult'], true, 44.6744420, -93.0618910);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Minneapolis MSA', 'Hennepin', 'MN', 'Hennepin County', '(Minneapolis)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 45.0076760, -93.4719180);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Minneapolis MSA', 'Ramsey', 'MN', 'Ramsey County', NULL, ARRAY['Active Adult'], true, 45.0155050, -93.0988930);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Minneapolis MSA', 'Scott', 'MN', 'Scott County', NULL, ARRAY['Active Adult'], true, 44.6550830, -93.5387880);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Minneapolis MSA', 'Washington', 'MN', 'Washington County', NULL, ARRAY['Active Adult'], true, 45.0491710, -92.8949540);

-- Missouri Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Kansas City, MO MSA', 'Cass', 'MO', 'Cass County, MO', NULL, ARRAY['Active Adult'], true, 38.6449820, -94.3509380);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Kansas City, MO MSA', 'Clay', 'MO', 'Clay County, MO', NULL, ARRAY['Active Adult'], true, 39.3190680, -94.4216000);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Kansas City, MO MSA', 'Jackson', 'MO', 'Jackson County, MO', '(Kansas City)', ARRAY['Active Adult', 'BTR'], true, 39.0119430, -94.3476120);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Kansas City, MO MSA', 'Platte', 'MO', 'Platte County, MO', NULL, ARRAY['Active Adult'], true, 39.4053610, -94.7768560);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('St. Louis, MO MSA', 'Franklin', 'MO', 'Franklin County, MO', NULL, ARRAY['Active Adult'], true, 38.4335840, -91.0172730);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('St. Louis, MO MSA', 'Jefferson', 'MO', 'Jefferson County, MO', NULL, ARRAY['Active Adult'], true, 38.2843640, -90.5230770);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('St. Louis, MO MSA', 'St. Charles', 'MO', 'St. Charles County, MO', NULL, ARRAY['Active Adult'], true, 38.7862870, -90.6410430);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('St. Louis, MO MSA', 'St. Louis', 'MO', 'St. Louis County, MO', '(St. Louis)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 38.6582480, -90.3161000);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('St. Louis, MO MSA', 'St. Louis City', 'MO', 'St. Louis City', NULL, ARRAY['Active Adult'], true, 38.6272730, -90.1978890);

-- North Carolina Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Charlotte MSA', 'Cabarrus', 'NC', 'Cabarrus County, NC', NULL, ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 35.3821240, -80.5446390);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Charlotte MSA', 'Gaston', 'NC', 'Gaston County, NC', NULL, ARRAY['Active Adult'], true, 35.2968950, -81.1508350);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Charlotte MSA', 'Iredell', 'NC', 'Iredell County, NC', NULL, ARRAY['Active Adult'], true, 35.7986280, -80.8697230);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Charlotte MSA', 'Lincoln', 'NC', 'Lincoln County, NC', NULL, ARRAY['Active Adult'], true, 35.4861390, -81.2080050);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Charlotte MSA', 'Mecklenburg', 'NC', 'Mecklenburg County, NC', '(Charlotte)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments', 'Lot Development', 'Affordable Housing'], true, 35.2589930, -80.8295130);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Charlotte MSA', 'Rowan', 'NC', 'Rowan County, NC', NULL, ARRAY['Active Adult'], true, 35.6421070, -80.5057940);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Charlotte MSA', 'Union', 'NC', 'Union County, NC', NULL, ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 34.9934390, -80.5451310);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Greensboro MSA', 'Guilford', 'NC', 'Guilford County, NC', '(Greensboro)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 36.0885130, -79.8193110);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Greensboro MSA', 'Randolph', 'NC', 'Randolph County, NC', NULL, ARRAY['Active Adult'], true, 35.7098620, -79.8096710);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Greensboro MSA', 'Rockingham', 'NC', 'Rockingham County, NC', NULL, ARRAY['Active Adult'], true, 36.3960970, -79.7787330);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Raleigh MSA and Triangle', 'Chatham', 'NC', 'Chatham County, NC', NULL, ARRAY['Active Adult'], true, 35.6983210, -79.2758160);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Raleigh MSA and Triangle', 'Durham', 'NC', 'Durham County, NC', '(Durham)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 36.0345210, -78.8786870);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Raleigh MSA and Triangle', 'Franklin', 'NC', 'Franklin County, NC', NULL, ARRAY['Active Adult'], true, 36.0990400, -78.2835750);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Raleigh MSA and Triangle', 'Johnston', 'NC', 'Johnston County, NC', NULL, ARRAY['Active Adult'], true, 35.5354560, -78.3703550);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Raleigh MSA and Triangle', 'Orange', 'NC', 'Orange County, NC', '(Chapel Hill)', ARRAY['Active Adult', 'BTR'], true, 36.0676840, -79.1004470);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Raleigh MSA and Triangle', 'Wake', 'NC', 'Wake County, NC', '(Raleigh)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments', 'Lot Development'], true, 35.7961060, -78.6420620);

-- Nebraska Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Omaha, NE MSA', 'Douglas', 'NE', 'Douglas County, NE', '(Omaha)', ARRAY['Active Adult', 'BTR'], true, 41.3133850, -96.1828350);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Omaha, NE MSA', 'Sarpy', 'NE', 'Sarpy County, NE', NULL, ARRAY['Active Adult'], true, 41.0975580, -96.1220260);

-- Nevada Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Las Vegas, NV MSA', 'Clark', 'NV', 'Clark County, NV', '(Las Vegas)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 36.2155260, -115.0128490);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Reno, NV MSA', 'Washoe', 'NV', 'Washoe County, NV', NULL, ARRAY['Active Adult'], true, 40.6649620, -119.6806880);

-- New Hampshire Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boston MSA', 'Hillsborough', 'NH', 'Hillsborough County, NH', NULL, ARRAY['Active Adult'], true, 42.9377370, -71.7077740);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boston MSA', 'Rockingham', 'NH', 'Rockingham County, NH', NULL, ARRAY['Active Adult'], true, 42.9840150, -71.0564100);

-- New Jersey Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Bergen', 'NJ', 'Bergen County, NJ', NULL, ARRAY['Active Adult'], true, 40.9620620, -74.0754490);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Essex', 'NJ', 'Essex County, NJ', NULL, ARRAY['Active Adult'], true, 40.7968390, -74.2376970);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Hudson', 'NJ', 'Hudson County, NJ', NULL, ARRAY['Active Adult'], true, 40.7453770, -74.0631540);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Middlesex', 'NJ', 'Middlesex County, NJ', NULL, ARRAY['Active Adult'], true, 40.4435680, -74.4124930);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Monmouth', 'NJ', 'Monmouth County, NJ', NULL, ARRAY['Active Adult'], true, 40.2956100, -74.1712990);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Ocean', 'NJ', 'Ocean County, NJ', NULL, ARRAY['Active Adult'], true, 39.9430740, -74.2774640);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Passaic', 'NJ', 'Passaic County, NJ', NULL, ARRAY['Active Adult'], true, 41.0479760, -74.3017760);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Somerset', 'NJ', 'Somerset County, NJ', NULL, ARRAY['Active Adult'], true, 40.5591240, -74.6459060);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Sussex', 'NJ', 'Sussex County, NJ', NULL, ARRAY['Active Adult'], true, 41.1382890, -74.6895880);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Union', 'NJ', 'Union County, NJ', NULL, ARRAY['Active Adult'], true, 40.6579530, -74.3059640);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Philadelphia MSA', 'Burlington', 'NJ', 'Burlington County, NJ', NULL, ARRAY['Active Adult'], true, 39.8749610, -74.6772020);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Philadelphia MSA', 'Camden', 'NJ', 'Camden County, NJ', NULL, ARRAY['Active Adult'], true, 39.8038700, -74.9488960);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Philadelphia MSA', 'Gloucester', 'NJ', 'Gloucester County, NJ', NULL, ARRAY['Active Adult'], true, 39.7094680, -75.1526010);

-- New Mexico Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Albuquerque, NM MSA', 'Bernalillo', 'NM', 'Bernalillo County, NM', '(Albuquerque)', ARRAY['Active Adult', 'BTR'], true, 35.0502710, -106.7426640);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Albuquerque, NM MSA', 'Sandoval', 'NM', 'Sandoval County, NM', NULL, ARRAY['Active Adult'], true, 35.6698040, -106.8993400);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Albuquerque, NM MSA', 'Valencia', 'NM', 'Valencia County, NM', NULL, ARRAY['Active Adult'], true, 34.7025020, -106.7848460);

-- New York Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Bronx', 'NY', 'Bronx County, NY', NULL, ARRAY['Active Adult'], true, 40.8466690, -73.8785640);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Kings', 'NY', 'Kings County, NY', '(Brooklyn)', ARRAY['Active Adult', 'BTR'], true, 40.6501040, -73.9495820);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Nassau', 'NY', 'Nassau County, NY', NULL, ARRAY['Active Adult'], true, 40.7406740, -73.5896810);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'New York', 'NY', 'New York County, NY', '(Manhattan)', ARRAY['Active Adult', 'BTR'], true, 40.7589880, -73.9846570);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Putnam', 'NY', 'Putnam County, NY', NULL, ARRAY['Active Adult'], true, 41.4270060, -73.7478920);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Queens', 'NY', 'Queens County, NY', NULL, ARRAY['Active Adult'], true, 40.7498320, -73.7976300);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Richmond', 'NY', 'Richmond County, NY', '(Staten Island)', ARRAY['Active Adult', 'BTR'], true, 40.5834350, -74.1496290);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Rockland', 'NY', 'Rockland County, NY', NULL, ARRAY['Active Adult'], true, 41.1489690, -74.0268110);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Suffolk', 'NY', 'Suffolk County, NY', NULL, ARRAY['Active Adult'], true, 40.9256540, -72.7468710);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('New York MSA', 'Westchester', 'NY', 'Westchester County, NY', NULL, ARRAY['Active Adult'], true, 41.1553650, -73.7583640);

-- Ohio Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Cincinnati, OH MSA', 'Brown', 'OH', 'Brown County, OH', NULL, ARRAY['Active Adult'], true, 38.9264850, -83.8778840);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Cincinnati, OH MSA', 'Butler', 'OH', 'Butler County, OH', NULL, ARRAY['Active Adult'], true, 39.4289700, -84.5689980);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Cincinnati, OH MSA', 'Clermont', 'OH', 'Clermont County, OH', NULL, ARRAY['Active Adult'], true, 39.0515850, -84.1416810);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Cincinnati, OH MSA', 'Hamilton', 'OH', 'Hamilton County, OH', '(Cincinnati)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 39.1950960, -84.5408240);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Cincinnati, OH MSA', 'Warren', 'OH', 'Warren County, OH', NULL, ARRAY['Active Adult'], true, 39.4399320, -84.1689310);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Cleveland, OH MSA', 'Cuyahoga', 'OH', 'Cuyahoga County, OH', '(Cleveland)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 41.4758560, -81.6971410);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Cleveland, OH MSA', 'Geauga', 'OH', 'Geauga County, OH', NULL, ARRAY['Active Adult'], true, 41.4874780, -81.1730780);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Cleveland, OH MSA', 'Lake', 'OH', 'Lake County, OH', NULL, ARRAY['Active Adult'], true, 41.6941080, -81.2547870);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Cleveland, OH MSA', 'Lorain', 'OH', 'Lorain County, OH', NULL, ARRAY['Active Adult'], true, 41.4417060, -82.1209250);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Cleveland, OH MSA', 'Medina', 'OH', 'Medina County, OH', NULL, ARRAY['Active Adult'], true, 41.1412950, -81.9320870);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Columbus, OH MSA', 'Delaware', 'OH', 'Delaware County, OH', NULL, ARRAY['Active Adult'], true, 40.2986850, -83.0073840);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Columbus, OH MSA', 'Fairfield', 'OH', 'Fairfield County, OH', NULL, ARRAY['Active Adult'], true, 39.7548740, -82.6364080);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Columbus, OH MSA', 'Franklin', 'OH', 'Franklin County, OH', '(Columbus)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 39.9830610, -83.0145230);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Columbus, OH MSA', 'Licking', 'OH', 'Licking County, OH', NULL, ARRAY['Active Adult'], true, 40.0711130, -82.5067320);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Columbus, OH MSA', 'Madison', 'OH', 'Madison County, OH', NULL, ARRAY['Active Adult'], true, 39.8902670, -83.4086480);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Columbus, OH MSA', 'Pickaway', 'OH', 'Pickaway County, OH', NULL, ARRAY['Active Adult'], true, 39.6320910, -82.9672540);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Columbus, OH MSA', 'Union', 'OH', 'Union County, OH', NULL, ARRAY['Active Adult'], true, 40.2949840, -83.3773250);

-- Oklahoma Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Oklahoma City, OK MSA', 'Canadian', 'OK', 'Canadian County, OK', NULL, ARRAY['Active Adult'], true, 35.5453280, -97.9802490);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Oklahoma City, OK MSA', 'Cleveland', 'OK', 'Cleveland County, OK', NULL, ARRAY['Active Adult'], true, 35.1988040, -97.3350940);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Oklahoma City, OK MSA', 'Grady', 'OK', 'Grady County, OK', NULL, ARRAY['Active Adult'], true, 34.9833800, -97.8847290);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Oklahoma City, OK MSA', 'Lincoln', 'OK', 'Lincoln County, OK', NULL, ARRAY['Active Adult'], true, 35.6751630, -96.9300810);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Oklahoma City, OK MSA', 'Logan', 'OK', 'Logan County, OK', NULL, ARRAY['Active Adult'], true, 35.9258440, -97.4410300);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Oklahoma City, OK MSA', 'McClain', 'OK', 'McClain County, OK', NULL, ARRAY['Active Adult'], true, 35.0066990, -97.4424660);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Oklahoma City, OK MSA', 'Oklahoma', 'OK', 'Oklahoma County, OK', '(Oklahoma City)', ARRAY['Active Adult', 'BTR'], true, 35.5522120, -97.3860250);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Tulsa, OK MSA', 'Creek', 'OK', 'Creek County, OK', NULL, ARRAY['Active Adult'], true, 35.9175560, -96.3703030);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Tulsa, OK MSA', 'Okmulgee', 'OK', 'Okmulgee County, OK', NULL, ARRAY['Active Adult'], true, 35.5992900, -96.0274930);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Tulsa, OK MSA', 'Osage', 'OK', 'Osage County, OK', NULL, ARRAY['Active Adult'], true, 36.6361240, -96.4057240);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Tulsa, OK MSA', 'Pawnee', 'OK', 'Pawnee County, OK', NULL, ARRAY['Active Adult'], true, 36.3305240, -96.6928730);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Tulsa, OK MSA', 'Rogers', 'OK', 'Rogers County, OK', NULL, ARRAY['Active Adult'], true, 36.3391900, -95.6096070);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Tulsa, OK MSA', 'Tulsa', 'OK', 'Tulsa County, OK', '(Tulsa)', ARRAY['Active Adult', 'BTR'], true, 36.1283990, -95.9025880);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Tulsa, OK MSA', 'Wagoner', 'OK', 'Wagoner County, OK', NULL, ARRAY['Active Adult'], true, 35.9509640, -95.5335960);

-- Oregon Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Portland, OR MSA', 'Clackamas', 'OR', 'Clackamas County, OR', NULL, ARRAY['Active Adult'], true, 45.1900780, -122.2489800);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Portland, OR MSA', 'Columbia', 'OR', 'Columbia County, OR', NULL, ARRAY['Active Adult'], true, 45.9430680, -123.0754240);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Portland, OR MSA', 'Multnomah', 'OR', 'Multnomah County, OR', '(Portland)', ARRAY['Active Adult', 'BTR'], true, 45.5426760, -122.4303700);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Portland, OR MSA', 'Washington', 'OR', 'Washington County, OR', NULL, ARRAY['Active Adult'], true, 45.5587110, -123.1067760);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Portland, OR MSA', 'Yamhill', 'OR', 'Yamhill County, OR', NULL, ARRAY['Active Adult'], true, 45.2429720, -123.3142190);

-- Pennsylvania Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Philadelphia MSA', 'Bucks', 'PA', 'Bucks County, PA', NULL, ARRAY['Active Adult'], true, 40.3381350, -75.1077110);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Philadelphia MSA', 'Chester', 'PA', 'Chester County, PA', NULL, ARRAY['Active Adult'], true, 39.9789970, -75.7646260);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Philadelphia MSA', 'Delaware', 'PA', 'Delaware County, PA', NULL, ARRAY['Active Adult'], true, 39.9155410, -75.4098380);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Philadelphia MSA', 'Montgomery', 'PA', 'Montgomery County, PA', NULL, ARRAY['Active Adult'], true, 40.2074370, -75.3679890);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Philadelphia MSA', 'Philadelphia', 'PA', 'Philadelphia County, PA', '(Philadelphia)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 40.0093760, -75.1333460);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Pittsburgh MSA', 'Allegheny', 'PA', 'Allegheny County, PA', '(Pittsburgh)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 40.4683540, -79.9708340);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Pittsburgh MSA', 'Butler', 'PA', 'Butler County, PA', NULL, ARRAY['Active Adult'], true, 40.9295070, -79.9455490);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Pittsburgh MSA', 'Washington', 'PA', 'Washington County, PA', NULL, ARRAY['Active Adult'], true, 40.2150980, -80.2565010);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Pittsburgh MSA', 'Westmoreland', 'PA', 'Westmoreland County, PA', NULL, ARRAY['Active Adult'], true, 40.3198900, -79.4762360);

-- Rhode Island Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boston MSA', 'Bristol', 'RI', 'Bristol County, RI', NULL, ARRAY['Active Adult'], true, 41.6900020, -71.2796250);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boston MSA', 'Kent', 'RI', 'Kent County, RI', NULL, ARRAY['Active Adult'], true, 41.6743310, -71.5869800);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boston MSA', 'Newport', 'RI', 'Newport County, RI', NULL, ARRAY['Active Adult'], true, 41.5278980, -71.2716920);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boston MSA', 'Providence', 'RI', 'Providence County, RI', NULL, ARRAY['Active Adult'], true, 41.8609730, -71.5002380);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Boston MSA', 'Washington', 'RI', 'Washington County, RI', NULL, ARRAY['Active Adult'], true, 41.4062960, -71.6160280);

-- South Carolina Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Charleston, SC MSA', 'Berkeley', 'SC', 'Berkeley County, SC', NULL, ARRAY['Active Adult'], true, 33.1851140, -79.9524750);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Charleston, SC MSA', 'Charleston', 'SC', 'Charleston County, SC', NULL, ARRAY['Active Adult'], true, 32.7882440, -80.0464210);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Charleston, SC MSA', 'Dorchester', 'SC', 'Dorchester County, SC', NULL, ARRAY['Active Adult'], true, 33.1307940, -80.4210070);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Charlotte MSA', 'Lancaster', 'SC', 'Lancaster County, SC', NULL, ARRAY['Active Adult'], true, 34.6896710, -80.7085580);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Charlotte MSA', 'York', 'SC', 'York County, SC', NULL, ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 35.0064740, -81.1668600);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Greenville, SC MSA', 'Greenville', 'SC', 'Greenville County, SC', '(Greenville)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 34.9407040, -82.3765780);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Greenville, SC MSA', 'Pickens', 'SC', 'Pickens County, SC', NULL, ARRAY['Active Adult'], true, 34.8663340, -82.7491550);

-- Tennessee Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Knoxville, TN MSA', 'Anderson', 'TN', 'Anderson County, TN', NULL, ARRAY['Active Adult'], true, 36.1098800, -84.1891720);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Knoxville, TN MSA', 'Blount', 'TN', 'Blount County, TN', NULL, ARRAY['Active Adult'], true, 35.6869670, -83.9292530);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Knoxville, TN MSA', 'Knox', 'TN', 'Knox County, TN', '(Knoxville)', ARRAY['Active Adult', 'BTR'], true, 36.0105850, -83.9362170);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Knoxville, TN MSA', 'Loudon', 'TN', 'Loudon County, TN', NULL, ARRAY['Active Adult'], true, 35.7324610, -84.3338000);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Memphis, TN MSA', 'Shelby', 'TN', 'Shelby County, TN', '(Memphis)', ARRAY['Active Adult', 'BTR'], true, 35.1586720, -89.8604700);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Nashville, TN MSA', 'Cannon', 'TN', 'Cannon County, TN', NULL, ARRAY['Active Adult'], true, 35.8081420, -86.0591630);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Nashville, TN MSA', 'Cheatham', 'TN', 'Cheatham County, TN', NULL, ARRAY['Active Adult'], true, 36.2597960, -87.0914070);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Nashville, TN MSA', 'Davidson', 'TN', 'Davidson County, TN', '(Nashville)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments', 'Lot Development'], true, 36.1674060, -86.7784270);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Nashville, TN MSA', 'Dickson', 'TN', 'Dickson County, TN', NULL, ARRAY['Active Adult'], true, 36.1425050, -87.3642350);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Nashville, TN MSA', 'Maury', 'TN', 'Maury County, TN', NULL, ARRAY['Active Adult'], true, 35.6145340, -87.0637700);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Nashville, TN MSA', 'Robertson', 'TN', 'Robertson County, TN', NULL, ARRAY['Active Adult'], true, 36.5256500, -86.8753640);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Nashville, TN MSA', 'Rutherford', 'TN', 'Rutherford County, TN', '(Murfreesboro)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 35.8456010, -86.3926340);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Nashville, TN MSA', 'Smith', 'TN', 'Smith County, TN', NULL, ARRAY['Active Adult'], true, 36.2622830, -85.9688180);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Nashville, TN MSA', 'Sumner', 'TN', 'Sumner County, TN', NULL, ARRAY['Active Adult'], true, 36.4647480, -86.4640930);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Nashville, TN MSA', 'Williamson', 'TN', 'Williamson County, TN', '(Franklin)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 35.8922860, -86.8698480);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Nashville, TN MSA', 'Wilson', 'TN', 'Wilson County, TN', NULL, ARRAY['Active Adult'], true, 36.1547840, -86.2946530);

-- Texas Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Austin, TX MSA', 'Bastrop', 'TX', 'Bastrop County, TX', NULL, ARRAY['Active Adult'], true, 30.1084900, -97.3154720);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Austin, TX MSA', 'Caldwell', 'TX', 'Caldwell County, TX', NULL, ARRAY['Active Adult'], true, 29.8351960, -97.6266520);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Austin, TX MSA', 'Hays', 'TX', 'Hays County, TX', NULL, ARRAY['Active Adult'], true, 30.0208920, -98.0332770);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Austin, TX MSA', 'Travis', 'TX', 'Travis County, TX', '(Austin)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 30.3254940, -97.7523820);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Austin, TX MSA', 'Williamson', 'TX', 'Williamson County, TX', NULL, ARRAY['Active Adult'], true, 30.6404790, -97.6049780);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Dallas MSA', 'Collin', 'TX', 'Collin County, TX', NULL, ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 33.1803730, -96.5704150);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Dallas MSA', 'Dallas', 'TX', 'Dallas County, TX', '(Dallas)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 32.7617020, -96.7984450);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Dallas MSA', 'Denton', 'TX', 'Denton County, TX', NULL, ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 33.2132360, -97.1330670);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Dallas MSA', 'Ellis', 'TX', 'Ellis County, TX', NULL, ARRAY['Active Adult'], true, 32.3426980, -96.8051970);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Dallas MSA', 'Johnson', 'TX', 'Johnson County, TX', NULL, ARRAY['Active Adult'], true, 32.3930740, -97.3692900);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Dallas MSA', 'Kaufman', 'TX', 'Kaufman County, TX', NULL, ARRAY['Active Adult'], true, 32.5920560, -96.2888140);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Dallas MSA', 'Rockwall', 'TX', 'Rockwall County, TX', NULL, ARRAY['Active Adult'], true, 32.8983720, -96.3817620);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Dallas MSA', 'Tarrant', 'TX', 'Tarrant County, TX', '(Fort Worth)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 32.7795070, -97.3463630);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Dallas MSA', 'Wise', 'TX', 'Wise County, TX', NULL, ARRAY['Active Adult'], true, 33.2174830, -97.6523020);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Houston MSA', 'Brazoria', 'TX', 'Brazoria County, TX', NULL, ARRAY['Active Adult'], true, 29.1691380, -95.4326590);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Houston MSA', 'Chambers', 'TX', 'Chambers County, TX', NULL, ARRAY['Active Adult'], true, 29.7305400, -94.7166240);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Houston MSA', 'Fort Bend', 'TX', 'Fort Bend County, TX', NULL, ARRAY['Active Adult'], true, 29.5260820, -95.7696750);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Houston MSA', 'Galveston', 'TX', 'Galveston County, TX', NULL, ARRAY['Active Adult'], true, 29.4557910, -94.8753920);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Houston MSA', 'Harris', 'TX', 'Harris County, TX', '(Houston)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 29.8577410, -95.3932630);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Houston MSA', 'Liberty', 'TX', 'Liberty County, TX', NULL, ARRAY['Active Adult'], true, 30.1645960, -94.7959570);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Houston MSA', 'Montgomery', 'TX', 'Montgomery County, TX', NULL, ARRAY['Active Adult'], true, 30.2988800, -95.4814890);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Houston MSA', 'Waller', 'TX', 'Waller County, TX', NULL, ARRAY['Active Adult'], true, 30.0545540, -95.9543900);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('San Antonio, TX MSA', 'Bexar', 'TX', 'Bexar County, TX', '(San Antonio)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 29.4497690, -98.5200710);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('San Antonio, TX MSA', 'Comal', 'TX', 'Comal County, TX', NULL, ARRAY['Active Adult'], true, 29.8105830, -98.2843220);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('San Antonio, TX MSA', 'Guadalupe', 'TX', 'Guadalupe County, TX', NULL, ARRAY['Active Adult'], true, 29.5739250, -97.9654690);

-- Utah Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Salt Lake City, UT MSA', 'Davis', 'UT', 'Davis County, UT', NULL, ARRAY['Active Adult'], true, 40.9893040, -112.0631830);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Salt Lake City, UT MSA', 'Salt Lake', 'UT', 'Salt Lake County, UT', '(Salt Lake City)', ARRAY['Active Adult', 'BTR'], true, 40.6689030, -111.9338130);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Salt Lake City, UT MSA', 'Tooele', 'UT', 'Tooele County, UT', NULL, ARRAY['Active Adult'], true, 40.4728920, -112.8494110);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Salt Lake City, UT MSA', 'Utah', 'UT', 'Utah County, UT', NULL, ARRAY['Active Adult'], true, 40.1135580, -111.6787950);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Salt Lake City, UT MSA', 'Weber', 'UT', 'Weber County, UT', NULL, ARRAY['Active Adult'], true, 41.2659460, -111.9633230);

-- Virginia Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Richmond, VA MSA', 'Goochland', 'VA', 'Goochland County, VA', NULL, ARRAY['Active Adult'], true, 37.7124580, -77.8839030);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Richmond, VA MSA', 'Hanover', 'VA', 'Hanover County, VA', NULL, ARRAY['Active Adult'], true, 37.7651840, -77.4675900);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Richmond, VA MSA', 'Henrico', 'VA', 'Henrico County, VA', NULL, ARRAY['Active Adult'], true, 37.5429260, -77.4008600);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Richmond, VA MSA', 'Powhatan', 'VA', 'Powhatan County, VA', NULL, ARRAY['Active Adult'], true, 37.5443200, -77.9207530);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Richmond, VA MSA', 'Richmond City', 'VA', 'Richmond City, VA', '(Richmond)', ARRAY['Active Adult', 'BTR'], true, 37.5385090, -77.4338890);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Washington, D.C. MSA', 'Alexandria City', 'VA', 'Alexandria City, VA', NULL, ARRAY['Active Adult'], true, 38.8199550, -77.0857640);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Washington, D.C. MSA', 'Arlington', 'VA', 'Arlington County, VA', NULL, ARRAY['Active Adult'], true, 38.8903860, -77.0841480);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Washington, D.C. MSA', 'Fairfax', 'VA', 'Fairfax County, VA', NULL, ARRAY['Active Adult'], true, 38.8464640, -77.3063660);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Washington, D.C. MSA', 'Loudoun', 'VA', 'Loudoun County, VA', NULL, ARRAY['Active Adult'], true, 39.0741270, -77.6459650);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Washington, D.C. MSA', 'Prince William', 'VA', 'Prince William County, VA', NULL, ARRAY['Active Adult'], true, 38.7276230, -77.5608430);

-- Washington Markets
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Seattle MSA', 'King', 'WA', 'King County, WA', '(Seattle)', ARRAY['Active Adult', 'BTR', 'Conventional Apartments'], true, 47.4903710, -121.8330960);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Seattle MSA', 'Pierce', 'WA', 'Pierce County, WA', NULL, ARRAY['Active Adult'], true, 47.0347740, -122.1242250);
INSERT INTO acquisition_markets (msa_name, county, state, full_county_name, city_note, product_types, is_active, latitude, longitude) VALUES ('Seattle MSA', 'Snohomish', 'WA', 'Snohomish County, WA', NULL, ARRAY['Active Adult'], true, 48.0446790, -121.7191840);
