-- ============================================================
-- LandLinq Published Site Export  2026-08-07T18:03:10Z
-- CRM Contacts: 4  |  Deals: 108
-- Demo data excluded.
-- ============================================================

-- ── CRM CONTACTS (BROKERS) ───────────────────────────────────
CREATE TABLE IF NOT EXISTS brokers_import (
  "id" TEXT,
  "first_name" TEXT,
  "last_name" TEXT,
  "email" TEXT,
  "phone" TEXT,
  "brokerage" TEXT,
  "company" TEXT,
  "markets_covered" TEXT,
  "state_region" TEXT,
  "years_experience" TEXT,
  "license_number" TEXT,
  "is_active" TEXT,
  "is_archived" TEXT,
  "sms_opt_in" TEXT,
  "preferred_contact" TEXT,
  "crm_tags" TEXT,
  "crm_notes" TEXT,
  "assigned_to" TEXT,
  "last_contacted_at" TEXT,
  "website_url" TEXT,
  "bio" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

INSERT INTO brokers_import ("id","first_name","last_name","email","phone","brokerage","company","markets_covered","state_region","years_experience","license_number","is_active","is_archived","sms_opt_in","preferred_contact","crm_tags","crm_notes","assigned_to","last_contacted_at","website_url","bio","created_at","updated_at") VALUES ('7ec6df1c-6f4e-4279-acb4-92d93f441e09', 'Bryse', 'Toothaker', 'btooth77@gmail.com', NULL, NULL, NULL, '{Not specified}', NULL, NULL, NULL, TRUE, FALSE, FALSE, 'email', NULL, NULL, NULL, NULL, NULL, NULL, '2026-08-05T20:21:57.153Z', '2026-08-05T20:21:57.153Z') ON CONFLICT DO NOTHING;
INSERT INTO brokers_import ("id","first_name","last_name","email","phone","brokerage","company","markets_covered","state_region","years_experience","license_number","is_active","is_archived","sms_opt_in","preferred_contact","crm_tags","crm_notes","assigned_to","last_contacted_at","website_url","bio","created_at","updated_at") VALUES ('b615189a-5593-4c8d-a2e6-1e21b5aa0488', 'Dorian', 'Bell', 'dorian@apexresi.com', NULL, NULL, NULL, '{Not specified}', NULL, NULL, NULL, TRUE, FALSE, FALSE, 'email', NULL, NULL, NULL, NULL, NULL, NULL, '2026-06-24T13:21:21.085Z', '2026-06-24T13:21:21.085Z') ON CONFLICT DO NOTHING;
INSERT INTO brokers_import ("id","first_name","last_name","email","phone","brokerage","company","markets_covered","state_region","years_experience","license_number","is_active","is_archived","sms_opt_in","preferred_contact","crm_tags","crm_notes","assigned_to","last_contacted_at","website_url","bio","created_at","updated_at") VALUES ('13ba281d-320c-4842-904c-41690ae59879', 'Aj', 'Klenk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, FALSE, FALSE, 'email', NULL, NULL, NULL, NULL, NULL, NULL, '2025-10-15T15:45:11.445Z', '2026-06-16T14:20:14.597Z') ON CONFLICT DO NOTHING;
INSERT INTO brokers_import ("id","first_name","last_name","email","phone","brokerage","company","markets_covered","state_region","years_experience","license_number","is_active","is_archived","sms_opt_in","preferred_contact","crm_tags","crm_notes","assigned_to","last_contacted_at","website_url","bio","created_at","updated_at") VALUES ('c3351faf-5dfb-4bd1-b374-ffa6533e90f9', 'Jack', 'Team', 'jack@catalystcp.com', NULL, NULL, NULL, 'Not specified', NULL, NULL, NULL, FALSE, FALSE, FALSE, 'email', '[Developer Network]', NULL, NULL, NULL, NULL, NULL, '2025-09-03T19:34:15.634Z', '2026-07-08T17:58:21.190Z') ON CONFLICT DO NOTHING;

-- ── DEALS ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS deals_import (
  "id" TEXT,
  "deal_number" TEXT,
  "status" TEXT,
  "classification" TEXT,
  "priority" TEXT,
  "address" TEXT,
  "city" TEXT,
  "state" TEXT,
  "zip" TEXT,
  "county" TEXT,
  "asking_price" TEXT,
  "size_acres" TEXT,
  "unit_count" TEXT,
  "yield_on_cost" TEXT,
  "qct_status" TEXT,
  "dda_status" TEXT,
  "oz_status" TEXT,
  "lihtc_score_total" TEXT,
  "product_types" TEXT,
  "analyst_notes" TEXT,
  "rejection_reason" TEXT,
  "deal_step" TEXT,
  "assigned_analyst" TEXT,
  "submission_method" TEXT,
  "broker_id" TEXT,
  "broker_name" TEXT,
  "broker_email" TEXT,
  "brokerage" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('ab536530-f4d5-4237-be80-56a20d849415', 460, 'under_review', 'dead', 'medium', '3500 Levon Drive', 'Wilmington', 'NC', 28412, 'New Hanover', NULL, 13.57, 46, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, NULL, NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-07-21T17:44:35.705Z', '2026-08-07T17:49:49.606Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('9f03cf66-f6e2-43e2-b138-698a8ccd660f', 455, 'clear_no', 'red', 'medium', '5350 Atlanta Highway', 'Bogart', 'GA', 30622, 'Clarke County', NULL, 35.05, NULL, NULL, 'NO', 'MDDA', 'NO', NULL, '[]', NULL, 'Found 5 multifamily properties within 3 miles, but none meet our acquisition criteria (built 2020+ with 150+ units). The market here is composed of older or smaller assets that don''t reflect institutional multifamily benchmarks.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Properties found nearby:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Cottages at Ridge Pointe — 1.8 mi: built 2019 (need 2020+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Wellington Park — 2.1 mi: built 1995 (need 2020+)', '112 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• 0012 -  WELLINGTON PARK - POWER FAM PRTNSHP — 2.2 mi: built 1993 (need 2020+)', '112 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Rev3 at Mill Creek — 2.6 mi: 90 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Meadowland — 2.6 mi: built 1984 (need 2020+)', '60 units (need 150+),,Austin Blondell,analyst_quick_add,,,,,2026-07-21T17:02:06.480Z,2026-07-23T15:35:52.648Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('769e7623-6032-4533-8b74-67bac7be1d4e', 449, 'pending_review', 'unclassified', 'medium', '1648 Loves Ln', 'Charlotte', 'NC', 28216, 'Mecklenburg', NULL, 34.22, 161, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, NULL, NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-07-20T18:57:35.590Z', '2026-08-07T17:52:00.142Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('98d46efe-73d6-4a1b-a99a-cd4a4ea91709', 444, 'clear_no', 'red', 'medium', '4537 W Market St', 'Greensboro', 'NC', 27407, 'Guilford County', 5000000.00, 7.95, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, '1968 vintage is below the 2000 minimum for acquisitions', NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-07-17T20:07:40.274Z', '2026-08-07T17:53:34.723Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('29db12c2-b5ba-4c2a-bc02-1bd281bca57a', 429, 'clear_no', 'red', 'medium', 'Highlands Glen Drive Phase 5', 'Shallotte', 'NC', 28470, 'Brunswick County', 3000000.00, 20.30, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, 'Found 1 comparable property meeting age/size criteria (2020+, 150+ units), but market rents don''t support our $1.75/sqft minimum:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• The Tides of Shallotte: $1.60/sqft ($0.15 below minimum) — 2024 vintage', '294 units', '0.8 mi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Best market rent in this area is $1.60/sqft — $0.15/sqft short of our minimum. This gap would materially impact development economics.,,Austin Blondell,analyst_quick_add,,,,,2026-07-10T18:04:55.656Z,2026-08-07T17:56:17.062Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('4e974cad-def4-4c90-bc14-6cda70931ab0', 421, 'under_review', 'yellow', 'medium', '151 Parkway North', 'Newnan', 'GA', 30265, 'Coweta', NULL, 17.30, 192, NULL, 'N/A', 'NO', NULL, NULL, '[]', NULL, NULL, NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-07-09T21:17:27.135Z', '2026-07-16T17:20:23.490Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('45b2051b-daa5-493d-8036-bec42214723e', 414, 'clear_no', 'red', 'medium', '0 lefty rd', 'Kenly', 'NC', 27542, NULL, 1050000.00, 96.00, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', '1,700+/-'' of Paved Road Frontage', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Excellent Location within Kenly ETJ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Underground Power', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Rocked Entrance Road,Found 2 multifamily properties within 3 miles', 'but none meet our acquisition criteria (built 2020+ with 150+ units). The market here is composed of older or smaller assets that don''t reflect institutional multifamily benchmarks.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Properties found nearby:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• KENLY COURT APARTMENTS — 0.9 mi: built 1979 (need 2020+)', '48 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• KENLY VILLAGE APTS — 1.1 mi: 24 units (need 150+),,Austin Blondell,analyst_quick_add,,,,,2026-07-08T19:58:46.142Z,2026-08-07T17:58:28.537Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('a214a4dd-9aeb-41cf-ab95-464be763bbf9', 401, 'clear_no', 'red', 'medium', 'Coordinates: 35.850778, -79.087833', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NO', 'NO', 'NO', 19, '[]', NULL, 'Found 1 multifamily property within 3 miles, but none meet our acquisition criteria (built 2020+ with 150+ units). The market here is composed of older or smaller assets that don''t reflect institutional multifamily benchmarks.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Properties found nearby:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• 76 Bell Cir — 0.4 mi: built 1990 (need 2020+)', '19 units (need 150+),,Austin Blondell,analyst_quick_add,,,,,2026-07-06T13:23:52.624Z,2026-07-06T17:58:10.806Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('dc8275c1-37ba-4761-8e55-8ea7bb165fbe', 397, 'clear_no', 'red', 'medium', 'Currituck County NLR Opp', 'Jarvisburg', 'NC', 27964, 'Currituck', 599000.00, 41.42, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, 'Property located in Currituck County, NC is not within Catalyst''s target acquisition markets. We are currently only acquiring in specific MSAs for Active Adult, BTR/Conventional Apartments, and Lot Development projects.', NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-07-02T16:03:05.264Z', '2026-08-07T18:00:40.790Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('f71f0954-9b84-4bb4-97de-88e17be4a2e2', 396, 'clear_no', 'red', 'medium', '1817 LAKESIDE DR', 'Franklin', 'NC', 28734, 'Macon', 1500000.00, 42.49, NULL, NULL, 'NO', 'NMDDA', 'NO', NULL, '[]', NULL, 'Found 7 multifamily properties within 3 miles, but none meet our acquisition criteria (built 2020+ with 150+ units). The market here is composed of older or smaller assets that don''t reflect institutional multifamily benchmarks.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Properties found nearby:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• HOLLY HAVEN — 1.2 mi: built 2004 (need 2020+)', '48 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• 43 Heritage Hollow — 1.4 mi: built 1977 (need 2020+)', '22 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• ULCO BLUFFS APARTMENTS — 1.7 mi: built 1983 (need 2020+)', '38 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Indigo Apartments — 2.4 mi: built 2017 (need 2020+)', '48 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• ORCHARD VIEW APTS — 2.7 mi: 48 units (need 150+),,Austin Blondell,analyst_quick_add,,,,,2026-07-02T15:55:18.120Z,2026-08-07T18:00:58.498Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('fb65bf59-9541-42f8-9429-673de4d5af36', 395, 'clear_no', 'red', 'medium', '595 Rock Creek Ridge', 'Bakersville', 'NC', 28705, 'Mitchell', NULL, 20.58, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, 'Found 9 multifamily properties within 3 miles, but none meet our acquisition criteria (built 2020+ with 150+ units). The market here is composed of older or smaller assets that don''t reflect institutional multifamily benchmarks.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Properties found nearby:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Ridge Run Apartments — 0.3 mi: built 2001 (need 2020+)', '48 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• RIDGE RUN APTS — 0.4 mi: 48 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Chimneys Apartments — 0.5 mi: built 1994 (need 2020+)', '112 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• HEATHFIELD APTS — 0.6 mi: built 1989 (need 2020+)', '72 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• UWHARRIE TRAIL — 0.7 mi: 80 units (need 150+),,Austin Blondell,analyst_quick_add,,,,,2026-07-02T15:53:20.785Z,2026-08-07T18:01:16.832Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('d33edec0-f629-4382-9c93-cefaaa5226e0', 394, 'clear_no', 'red', 'medium', '568 NC HIGHWAY 62 E', 'Pleasant Garden', 'NC', 27313, 'Guilford', 1973400.00, 47.35, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, 'Found 3 multifamily properties within 3 miles, but none meet our acquisition criteria (built 2020+ with 150+ units). The market here is composed of older or smaller assets that don''t reflect institutional multifamily benchmarks.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Properties found nearby:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Shiloh Ridge — 3.9 mi: 5 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• 235 235 A-X East Dameron Avenue — 4.5 mi: 24 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• 235 A-X East Dameron Avenue — 4.5 mi: 24 units (need 150+),,Austin Blondell,analyst_quick_add,,,,,2026-07-02T15:50:10.643Z,2026-08-07T18:01:37.088Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('44bc7053-f360-4b89-af83-53ca8bacfbbb', 387, 'clear_no', 'red', 'medium', '4136 ROSE CREEK RD', 'Franklin', 'NC', 28734, 'Macon', 979000.00, 85.84, NULL, NULL, 'NO', 'NMDDA', 'NO', NULL, '[]', NULL, 'Property located in Macon County, NC is not within Catalyst''s target acquisition markets. We are currently only acquiring in specific MSAs for Active Adult, BTR/Conventional Apartments, and Lot Development projects.', NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-07-02T13:19:28.316Z', '2026-08-07T18:03:11.114Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('455f506d-fa4d-4bb2-b432-1bace27276ae', 386, 'clear_no', 'red', 'medium', '628 Faith Farm Rd', 'Rockwell', 'NC', NULL, 'rowan', 1229760.00, 95.00, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, 'Found 2 multifamily properties within 3 miles, but none meet our acquisition criteria (built 2020+ with 150+ units). The market here is composed of older or smaller assets that don''t reflect institutional multifamily benchmarks.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Properties found nearby:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• RO-WELL APARTMENTS — 1.0 mi: built 1987 (need 2020+)', '36 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• White Rock Gardens — 4.7 mi: built 1984 (need 2020+)', '30 units (need 150+),,Austin Blondell,analyst_quick_add,,,,,2026-07-02T13:16:52.680Z,2026-08-07T18:03:30.802Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('9d826954-f388-47b0-9dbe-eb878144c016', 382, 'clear_no', 'red', 'medium', 'Spring Branch NLR opp', NULL, 'NC', 27542, 'Johnston', 273675.00, NULL, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, 'Found 3 multifamily properties within 3 miles, but none meet our acquisition criteria (built 2020+ with 150+ units). The market here is composed of older or smaller assets that don''t reflect institutional multifamily benchmarks.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Properties found nearby:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Creekridge Apartments — 1.7 mi: 25 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• CREEKRIDGE APTS — 4.7 mi: 25 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• MOORLAND COVE — 4.7 mi: 60 units (need 150+),,Austin Blondell,analyst_quick_add,,,,,2026-07-02T13:12:23.581Z,2026-07-08T20:01:38.671Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('8ca6142b-512f-4a87-a6b4-ef656aec3be9', 379, 'clear_no', 'red', 'medium', '0 COLON RD PC 9/70E DB 734/01 (DOT ROWY)', 'sanford', 'NC', 27330, 'sanford', NULL, NULL, NULL, NULL, 'YES', 'NO', 'NO', 61, '[]', 'Sanford Plating Co is a superfund site located at 1/4 Mi. Sw Of Colon & Rt.5, Sanford, NC 27330. The Environmental Protection Agency (EPA) identifies sites such as Sanford Plating Co because they pose or had once posed a potential risk to human health and/or the environment due to contamination by one or more hazardous wastes. Sanford Plating Co is currently registered as an Archived superfund site by the EPA and does not require any further clean up action or further investigation.', 'Property located in sanford County, NC is not within Catalyst''s target acquisition markets. We are currently only acquiring in specific MSAs for Active Adult, BTR/Conventional Apartments, and Lot Development projects.', NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-07-01T16:07:57.301Z', '2026-07-08T20:01:41.672Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('84ca7785-c735-402b-b48c-3c9ac56875c5', 371, 'clear_no', 'red', 'medium', 'Coordinates: 34.962616, -80.106426', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'YES', 'NO', 'NO', 23, '[]', NULL, 'Property located in Anson County, NC is not within Catalyst''s target acquisition markets. We are currently only acquiring in specific MSAs for Active Adult, BTR/Conventional Apartments, and Lot Development projects.', NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-06-29T20:14:49.764Z', '2026-07-13T18:24:17.254Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('66b18d17-fd2b-48dd-83a4-d6d82e510175', 356, 'clear_no', 'red', 'medium', '1 Eastern Way', 'Durham', 'NC', 27703, 'Wayne', NULL, 0.33, NULL, NULL, 'YES', 'NO', 'NO', 57, '[]', NULL, 'Property located in Wayne County, NC is not within Catalyst''s target acquisition markets. We are currently only acquiring in specific MSAs for Active Adult, BTR/Conventional Apartments, and Lot Development projects.', NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-06-24T16:27:41.506Z', '2026-07-13T18:24:23.141Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('f49187c0-634f-4f9e-872d-61455b627be8', 351, 'clear_no', 'red', 'medium', '975 Ziglar Rd', 'Winston-Salem', 'NC', 27105, 'Forsyth County', NULL, 20.83, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, 'Found 10 multifamily properties within 3 miles, but none meet our acquisition criteria (built 2020+ with 150+ units). The market here is composed of older or smaller assets that don''t reflect institutional multifamily benchmarks.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Properties found nearby:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Lofts at Mill Creek Apartments — 0.4 mi: built 1978 (need 2020+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Beltway Park at Winston — 0.5 mi: built 1984 (need 2020+)', '78 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Abbington Gardens — 0.6 mi: built 2016 (need 2020+)', '96 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Abbington Gardens of Winston-Salem — 0.6 mi: 96 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Mill Creek Flats — 1.2 mi: built 1984 (need 2020+),,Austin Blondell,analyst_quick_add,,,,,2026-06-22T18:28:56.003Z,2026-07-20T19:02:43.943Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('0f88d5b8-d857-42fc-b41a-77a1556249c5', 285, 'clear_no', 'red', 'medium', 'Parcel ID: 2103401008', NULL, 'GA', NULL, 'Savannah', NULL, NULL, NULL, NULL, 'N/A', 'NO', NULL, NULL, '[]', NULL, 'Property located in Savannah County, GA is not within Catalyst''s target acquisition markets. We are currently only acquiring in specific MSAs for Active Adult, BTR/Conventional Apartments, and Lot Development projects.', NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-05-05T14:44:43.671Z', '2026-07-13T18:25:30.253Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('8a926298-3cb3-435f-90d2-0e3abe755502', 275, 'clear_no', 'red', 'medium', '5315 SOARING EAGLE LN', 'mint hill', 'NC', 28227, 'Mecklenburg County', NULL, 4.14, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, 'Found 5 multifamily properties within 3 miles, but none meet our acquisition criteria (built 2020+ with 150+ units). The market here is composed of older or smaller assets that don''t reflect institutional multifamily benchmarks.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Properties found nearby:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• 4229 PEGGY LN — 0.8 mi: built 1967 (need 2020+)', '5 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Holiday Willow Grove — 2.1 mi: built 2007 (need 2020+)', '120 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• 13931 Thompson Road — 2.1 mi: 6 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Album Matthews 55+ Active Adult Apartments — 2.3 mi: 128 units (need 150+)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Residences at West Mint — 2.3 mi: built 1998 (need 2020+),,Austin Blondell,analyst_quick_add,,,,,2026-04-28T20:29:12.460Z,2026-07-09T14:28:50.283Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('872096a3-c03d-42e7-92a8-73e23537bd20', 274, 'under_review', 'green', 1, '1023 YORKMONT RD', 'CHARLOTTE', 'NC', 28217, 'Mecklenburg County', NULL, 7.92, NULL, '3.95%', 'NO', 'NO', 'NO', NULL, '[aa-4-story-flats]', 'Dorian to call owner to see if interested in selling.', NULL, 'Initial UW', 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-04-28T20:25:21.984Z', '2026-07-13T17:30:54.708Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('a60ae596-dc11-4d48-b499-118a916be671', 273, 'pending_review', 'unclassified', 'medium', '5606 WILGROVE-MINT HILL RD', 'MINT HILL', 'NC', 28227, 'Mecklenburg', NULL, 6.51, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, NULL, NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-04-28T20:24:39.383Z', '2026-07-09T14:29:29.286Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('c9a2a032-0507-48e4-8a70-b67bee8d6dd9', 272, 'pending_review', 'unclassified', 'medium', '5520 WILGROVE-MINT HILL RD', 'MINT HILL', 'NC', 28227, 'Mecklenburg', NULL, 4.92, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, NULL, NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-04-28T20:23:38.234Z', '2026-07-08T18:34:42.580Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('be0857c8-15cc-40aa-acc3-0de2f4060029', 271, 'clear_no', 'red', 'medium', '8045 WILSON WOODS DR', 'MINT HILL', 'NC', 28227, 'Mecklenburg County', NULL, 50.50, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, 'Found 1 comparable property meeting age/size criteria (2020+, 150+ units), but market rents don''t support our $1.75/sqft minimum:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Lemmond Farm: $1.47/sqft ($0.28 below minimum) — 2020 vintage', '336 units', '1.3 mi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Best market rent in this area is $1.47/sqft — $0.28/sqft short of our minimum. This gap would materially impact development economics.,,Austin Blondell,analyst_quick_add,,,,,2026-04-28T20:22:55.072Z,2026-07-06T17:50:33.245Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('caee3443-d1ba-4b7a-ba60-7bed0e387b00', 270, 'clear_no', 'red', 'medium', '10900 PINE GROVE AV', 'MINT HILL', 'NC', 28227, 'Mecklenburg County', NULL, 29.84, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, 'Found 1 comparable property meeting age/size criteria (2020+, 150+ units), but market rents don''t support our $1.75/sqft minimum:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Lemmond Farm: $1.47/sqft ($0.28 below minimum) — 2020 vintage', '336 units', '0.8 mi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Best market rent in this area is $1.47/sqft — $0.28/sqft short of our minimum. This gap would materially impact development economics.,,Austin Blondell,analyst_quick_add,,,,,2026-04-28T20:21:51.687Z,2026-07-06T17:51:01.359Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('85cfda3c-9b78-4b2f-9d5b-733ddeaf52dc', 269, 'pending_review', 'unclassified', 'medium', '6200 WILGROVE-MINT HILL RD', 'MINT HILL', 'NC', 28227, 'Mecklenburg County', NULL, 7.42, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, NULL, NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-04-28T20:21:00.445Z', '2026-07-06T17:51:24.089Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('c0bdd40a-6365-4a99-8036-65b5a392a1c3', 265, 'under_review', 'yellow', 'medium', 'Parcel ID: 201-031-17', 'Huntersville', 'NC', NULL, 'Mecklenburg', NULL, NULL, NULL, '4 Story AA - 3.42%', 'NO', 'NO', 'NO', NULL, '[aa-4-story-flats]', NULL, NULL, NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-04-28T17:13:40.354Z', '2026-07-13T17:29:23.107Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('276dfeb3-fa44-4c2c-ac54-65e2a4fae83e', 246, 'under_review', 'red', 'medium', '1 Medical Center Dr SW', 'Supply', 'NC', 28462, 'Brunswick', NULL, 31.60, NULL, NULL, 'NO', 'NO', 'NO', NULL, '[]', NULL, NULL, NULL, 'Austin Blondell', 'analyst_quick_add', NULL, NULL, NULL, NULL, '2026-04-22T18:29:27.014Z', '2026-07-13T18:25:39.712Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('ba5b7d22-3bb4-452a-9823-09e08b334fb4', 221, 'clear_no', 'red', 'medium', '5613 Clark Rd', 'Harrison', 'TN', 37341, 'Hamilton', NULL, NULL, NULL, NULL, 'NO', 'NO', 'NO', NULL, NULL, NULL, 'Found 1 comparable property meeting age/size criteria (2020+, 150+ units), but market rents don''t support our $1.75/sqft minimum:', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('• Anchor Point: $1.51/sqft ($0.24 below minimum) — 2024 vintage', '156 units', '1.0 mi', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('Best market rent in this area is $1.51/sqft — $0.24/sqft short of our minimum. This gap would materially impact development economics.,,Austin Blondell,email,,,,,2026-04-10T14:59:41.045Z,2026-06-25T17:49:43.995Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('5ec187b2-b427-48a1-a5c1-f2e812cb5a93', 219, 'pending_review', 'unclassified', 'medium', '0 Dutchtown Rd', 'Knoxville', 'TN', 37932, 'Knox', NULL, NULL, NULL, NULL, 'NO', 'MDDA', 'NO', NULL, NULL, NULL, NULL, NULL, 'Austin Blondell', 'email', NULL, NULL, NULL, NULL, '2026-04-08T16:12:41.555Z', '2026-07-01T17:34:34.561Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('3562974f-01cc-43c7-a68a-3ee7e8f3a641', 218, 'clear_no', 'red', 'medium', '5139 Spring Valley Dr', 'Grantham', 'NH', 03753, 'Sullivan County', NULL, NULL, NULL, NULL, 'NO', 'NMDDA', 'NO', NULL, NULL, NULL, 'Property located in Sullivan County, NH is not within Catalyst''s target acquisition markets. We are currently only acquiring in specific MSAs for Active Adult, BTR/Conventional Apartments, and Lot Development projects.', NULL, 'Austin Blondell', 'email', NULL, NULL, NULL, NULL, '2026-04-08T16:12:33.753Z', '2026-07-01T17:35:36.566Z') ON CONFLICT DO NOTHING;
INSERT INTO deals_import ("id","deal_number","status","classification","priority","address","city","state","zip","county","asking_price","size_acres","unit_count","yield_on_cost","qct_status","dda_status","oz_status","lihtc_score_total","product_types","analyst_notes","rejection_reason","deal_step","assigned_analyst","submission_method","broker_id","broker_name","broker_email","brokerage","created_at","updated_at") VALUES ('b5ec4e61-0552-43c1-bbd4-6f6acf848563', 9, 'clear_no', 'dead', 'medium', '2201 Mechanic Street', 'Charlotte', 'NC', 28205, 'Mecklenburg', 40.00, 25.25, NULL, NULL, 'NO', 'NO', 'NO', NULL, NULL, NULL, 'Found 12 multifamily properties within 3 miles, but none meet our criteria (built 2020+ with 150+ units). The properties in this area are older or smaller than our investment requirements.', NULL, 'Austin Blondell', 'email', '13ba281d-320c-4842-904c-41690ae59879', 'Aj Klenk', NULL, NULL, '2025-12-11T20:45:07.776Z', '2026-06-25T17:49:48.205Z') ON CONFLICT DO NOTHING;
