import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import {
  MapPin, Building2, LogOut, ChevronRight, Search,
  DollarSign, Layers, Eye, X, Ruler, Users,
  Download, ExternalLink, Settings, Phone, Mail, Pencil,
  CheckCircle, Plus, Trash2, TrendingUp, Building,
} from "lucide-react";
import Footer from "@/components/footer";

const landlinqLogo = "/assets/landlinq-email-logo.png";

const US_STATES = [
  "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA",
  "HI","ID","IL","IN","IA","KS","KY","LA","ME","MD",
  "MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ",
  "NM","NY","NC","ND","OH","OK","OR","PA","RI","SC",
  "SD","TN","TX","UT","VT","VA","WA","WV","WI","WY",
];

type BrokerAccount = {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  brokerage?: string;
  phone?: string;
  targetStates: string[];
  targetMsas: string[];
  targetCities: string[];
};

type Deal = {
  id: string;
  address: string;
  city?: string;
  state?: string;
  zip?: string;
  county?: string;
  msa_name?: string;
  classification?: string;
  product_types?: any;
  size_acres?: string;
  unit_count?: number;
  max_units_by_zoning?: number;
  asking_price?: string;
  zoning?: string;
  has_entitlements?: boolean;
  property_name?: string;
  deal_type?: string;
  created_at: string;
  investment_memo_url?: string | null;
  yield_on_cost?: string | null;
  projected_rent_per_sf?: string | null;
  top_rent_psf?: string | null;
};



function parseYoc(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const labeled = raw.match(/YOC\s*[-:]?\s*(\d+\.?\d*)\s*%/i);
  if (labeled) return `${parseFloat(labeled[1]).toFixed(1)}%`;
  const plain = raw.match(/(\d+\.?\d*)\s*%/);
  if (plain) return `${parseFloat(plain[1]).toFixed(1)}%`;
  return null;
}

function getMemoUrl(deal: Deal): string | null {
  // Investment memo generated by analyst (stored in object storage, served via broker proxy)
  if (deal.investment_memo_url) return `/api/broker-portal/deals/${deal.id}/memo`;
  return null;
}

function formatProductType(raw: string): string {
  const lower = raw.toLowerCase();
  if (lower.startsWith("btr-th") || lower.includes("btr-town") || lower.includes("btr_th")) return "BTR TH";
  if (lower.startsWith("btr-sf") || lower.includes("btr-single") || lower.includes("btr_sf")) return "BTR SF";
  if (lower.startsWith("btr")) return "BTR TH"; // fallback for any other BTR
  return raw
    .replace(/-/g, " ")
    .replace(/\b\w/g, c => c.toUpperCase());
}

function DealCard({ deal, onClick }: { deal: Deal; onClick: () => void }) {
  const types: string[] = Array.isArray(deal.product_types)
    ? deal.product_types
    : (typeof deal.product_types === "string" ? JSON.parse(deal.product_types || "[]") : []);
  const memoUrl = getMemoUrl(deal);
  const yoc = parseYoc(deal.yield_on_cost);
  const rentPerSf = deal.projected_rent_per_sf ? parseFloat(deal.projected_rent_per_sf) : null;
  const topRentPsf = deal.top_rent_psf ? parseFloat(deal.top_rent_psf) : null;

  return (
    <div className="bg-white border border-gray-200 rounded-xl p-5 hover:shadow-md hover:border-[#0d2d4e]/40 transition-all group flex flex-col">
      <div
        className="flex items-start justify-between gap-3 mb-3 cursor-pointer flex-1"
        onClick={onClick}
      >
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1 flex-wrap">
            {deal.deal_type && (
              <span className="text-[10px] font-medium px-2 py-0.5 rounded-full bg-[#0d2d4e]/8 text-[#0d2d4e]">
                {deal.deal_type.charAt(0).toUpperCase() + deal.deal_type.slice(1)}
              </span>
            )}
          </div>
          <h3 className="font-semibold text-[#0d2d4e] text-sm leading-snug truncate">
            {deal.property_name || deal.address}
          </h3>
          {deal.property_name && (
            <p className="text-xs text-gray-500 truncate mt-0.5">{deal.address}</p>
          )}
          <div className="flex items-center gap-1 mt-1 text-xs text-gray-500">
            <MapPin className="w-3 h-3" />
            {[deal.city, deal.state].filter(Boolean).join(", ")}
            {deal.county && <span className="text-gray-400">· {deal.county} Co.</span>}
          </div>
        </div>
        <ChevronRight className="w-4 h-4 text-gray-300 group-hover:text-[#0d2d4e] flex-shrink-0 mt-1 transition-colors" />
      </div>

      <div className="flex flex-wrap gap-3 text-xs text-gray-600 mt-auto pt-3 border-t border-gray-100">
        {deal.size_acres && (
          <span className="flex items-center gap-1">
            <Ruler className="w-3 h-3 text-gray-400" />
            {parseFloat(deal.size_acres).toFixed(1)} ac
          </span>
        )}
        {(deal.unit_count || deal.max_units_by_zoning) && (
          <span className="flex items-center gap-1">
            <Users className="w-3 h-3 text-gray-400" />
            {deal.unit_count || deal.max_units_by_zoning} units
          </span>
        )}
        {deal.asking_price && (
          <span className="flex items-center gap-1 font-semibold text-[#0d2d4e]">
            <DollarSign className="w-3 h-3 text-[#0d2d4e]" />
            {parseInt(deal.asking_price) >= 1_000_000
              ? `${(parseInt(deal.asking_price) / 1_000_000).toFixed(2)}M`
              : `${parseInt(deal.asking_price).toLocaleString()}`}
          </span>
        )}
        {yoc && (
          <span className="flex items-center gap-1 font-semibold text-emerald-600">
            <TrendingUp className="w-3 h-3" />
            {yoc} YOC
          </span>
        )}
        {topRentPsf !== null && !isNaN(topRentPsf) && (
          <span className="flex items-center gap-1 font-semibold text-blue-600">
            <Building className="w-3 h-3" />
            ${topRentPsf.toFixed(2)}/sf mkt
          </span>
        )}
        {types.length > 0 && (
          <span className="flex items-center gap-1">
            <Layers className="w-3 h-3 text-gray-400" />
            {formatProductType(types[0])}
          </span>
        )}
      </div>

      {memoUrl && (
        <div className="mt-3 flex gap-2">
          <a
            href={memoUrl}
            target="_blank"
            rel="noopener noreferrer"
            onClick={e => e.stopPropagation()}
            className="flex-1 flex items-center justify-center gap-1.5 text-xs font-semibold bg-[#0d2d4e] text-white px-3 py-2 rounded-lg hover:bg-[#0d2d4e]/85 transition-colors"
          >
            <Eye className="w-3.5 h-3.5" /> View Investment Memo
          </a>
          <a
            href={memoUrl}
            download
            target="_blank"
            rel="noopener noreferrer"
            onClick={e => e.stopPropagation()}
            className="flex items-center justify-center gap-1.5 text-xs font-semibold border border-[#0d2d4e]/30 text-[#0d2d4e] px-3 py-2 rounded-lg hover:bg-[#0d2d4e]/5 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
          </a>
        </div>
      )}
    </div>
  );
}

function DealDetailModal({ deal, onClose }: { deal: Deal; onClose: () => void }) {
  const types: string[] = Array.isArray(deal.product_types)
    ? deal.product_types
    : (typeof deal.product_types === "string" ? JSON.parse(deal.product_types || "[]") : []);
  const memoUrl = getMemoUrl(deal);
  const yoc = parseYoc(deal.yield_on_cost);
  const topRentPsf = deal.top_rent_psf ? parseFloat(deal.top_rent_psf) : null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200 sticky top-0 bg-white rounded-t-2xl z-10">
          <div>
            <h2 className="font-bold text-[#0d2d4e] text-base leading-tight">
              {deal.property_name || deal.address}
            </h2>
            <p className="text-xs text-gray-500 mt-0.5">
              {[deal.city, deal.state, deal.zip].filter(Boolean).join(", ")}
            </p>
          </div>
          <button onClick={onClose} className="p-1.5 rounded hover:bg-gray-100 text-gray-400 hover:text-gray-600 transition-colors">
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="px-6 py-5 space-y-5">
          <div className="flex flex-wrap gap-2">
            {deal.deal_type && (
              <span className="text-xs font-medium px-3 py-1 rounded-full bg-[#0d2d4e]/10 text-[#0d2d4e]">
                {deal.deal_type.charAt(0).toUpperCase() + deal.deal_type.slice(1)}
              </span>
            )}
            {deal.has_entitlements && (
              <span className="text-xs font-medium px-3 py-1 rounded-full bg-green-50 text-green-700">
                Entitled
              </span>
            )}
          </div>

          {deal.investment_memo_url && (
            <div className="flex gap-2">
              <a
                href={`/api/broker-portal/deals/${deal.id}/memo`}
                target="_blank"
                rel="noopener noreferrer"
                className="flex-1 flex items-center justify-center gap-2 text-sm font-semibold bg-[#0d2d4e] text-white px-4 py-2.5 rounded-lg hover:bg-[#0d2d4e]/85 transition-colors"
              >
                <Eye className="w-4 h-4" /> View Investment Memo
              </a>
              <a
                href={`/api/broker-portal/deals/${deal.id}/memo`}
                download
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center justify-center gap-2 text-sm font-semibold border border-[#0d2d4e]/30 text-[#0d2d4e] px-4 py-2.5 rounded-lg hover:bg-[#0d2d4e]/5 transition-colors"
              >
                <Download className="w-4 h-4" />
              </a>
            </div>
          )}

          <div className="grid grid-cols-2 gap-4">
            {deal.size_acres && (
              <div className="bg-gray-50 rounded-lg p-3">
                <div className="text-[10px] text-gray-500 font-medium uppercase tracking-wide mb-1">Acreage</div>
                <div className="font-bold text-[#0d2d4e] text-lg">{parseFloat(deal.size_acres).toFixed(2)}</div>
                <div className="text-xs text-gray-500">acres</div>
              </div>
            )}
            {deal.asking_price && (
              <div className="bg-gray-50 rounded-lg p-3">
                <div className="text-[10px] text-gray-500 font-medium uppercase tracking-wide mb-1">Asking Price</div>
                <div className="font-bold text-[#0d2d4e] text-lg">${(parseInt(deal.asking_price) / 1000000).toFixed(2)}M</div>
                <div className="text-xs text-gray-500">${parseInt(deal.asking_price).toLocaleString()}</div>
              </div>
            )}
            {deal.unit_count && (
              <div className="bg-gray-50 rounded-lg p-3">
                <div className="text-[10px] text-gray-500 font-medium uppercase tracking-wide mb-1">Units</div>
                <div className="font-bold text-[#0d2d4e] text-lg">{deal.unit_count}</div>
                <div className="text-xs text-gray-500">estimated</div>
              </div>
            )}
            {deal.max_units_by_zoning && (
              <div className="bg-gray-50 rounded-lg p-3">
                <div className="text-[10px] text-gray-500 font-medium uppercase tracking-wide mb-1">Max by Zoning</div>
                <div className="font-bold text-[#0d2d4e] text-lg">{deal.max_units_by_zoning}</div>
                <div className="text-xs text-gray-500">units permitted</div>
              </div>
            )}
            {yoc && (
              <div className="bg-green-50 rounded-lg p-3">
                <div className="text-[10px] text-green-700 font-medium uppercase tracking-wide mb-1">Yield on Cost</div>
                <div className="font-bold text-green-700 text-lg">{yoc}</div>
                <div className="text-xs text-green-600">projected YOC</div>
              </div>
            )}
            {topRentPsf !== null && !isNaN(topRentPsf) && (
              <div className="bg-blue-50 rounded-lg p-3">
                <div className="text-[10px] text-blue-700 font-medium uppercase tracking-wide mb-1">Market Rent</div>
                <div className="font-bold text-blue-700 text-lg">${topRentPsf.toFixed(2)}</div>
                <div className="text-xs text-blue-600">top comps / sf</div>
              </div>
            )}
          </div>

          <div>
            <h3 className="text-xs font-semibold text-gray-600 uppercase tracking-wide mb-2">Location</h3>
            <div className="space-y-1 text-sm text-gray-700">
              <div>{deal.address}</div>
              <div>{[deal.city, deal.state, deal.zip].filter(Boolean).join(", ")}</div>
              {deal.county && <div className="text-gray-500">{deal.county} County</div>}
              {deal.msa_name && <div className="text-gray-500">{deal.msa_name} MSA</div>}
            </div>
          </div>

          {types.length > 0 && (
            <div>
              <h3 className="text-xs font-semibold text-gray-600 uppercase tracking-wide mb-2">Product Types</h3>
              <div className="flex flex-wrap gap-1.5">
                {types.map(t => (
                  <span key={t} className="text-xs bg-blue-50 text-blue-700 px-2.5 py-1 rounded-full font-medium">{formatProductType(t)}</span>
                ))}
              </div>
            </div>
          )}

          {deal.zoning && (
            <div>
              <h3 className="text-xs font-semibold text-gray-600 uppercase tracking-wide mb-2">Zoning</h3>
              <p className="text-sm text-gray-700">{deal.zoning}</p>
            </div>
          )}

          {!memoUrl && (
            <div className="bg-[#0d2d4e]/5 border border-[#0d2d4e]/10 rounded-xl p-4 text-center">
              <p className="text-sm text-[#0d2d4e] font-medium mb-1">Interested in this deal?</p>
              <p className="text-xs text-gray-500 mb-3">Reach out to receive the full underwriting and discuss next steps.</p>
              <a
                href="mailto:deals@landlinq.com?subject=Interest in Deal"
                className="inline-flex items-center gap-2 bg-[#0d2d4e] text-white text-xs font-semibold px-4 py-2 rounded-lg hover:bg-[#0d2d4e]/90 transition-colors"
              >
                <Mail className="w-3.5 h-3.5" /> Request Underwriting
              </a>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function ProfileModal({ account, onClose }: { account: BrokerAccount; onClose: () => void }) {
  const [firstName, setFirstName] = useState(account.firstName);
  const [lastName, setLastName] = useState(account.lastName);
  const [phone, setPhone] = useState(account.phone || "");
  const [brokerage, setBrokerage] = useState(account.brokerage || "");
  const [targetStates, setTargetStates] = useState<string[]>(account.targetStates || []);
  const [targetMsas, setTargetMsas] = useState<string[]>(account.targetMsas || []);
  const [targetCities, setTargetCities] = useState<string[]>(account.targetCities || []);
  const [cityInput, setCityInput] = useState("");
  const [msaInput, setMsaInput] = useState("");
  const [saved, setSaved] = useState(false);
  const [expandedStates, setExpandedStates] = useState<string[]>(account.targetStates || []);

  const { data: msaData } = useQuery<{ msasByState: Record<string, string[]> }>({
    queryKey: ["/api/public/msas-by-state"],
  });
  const msasByState = msaData?.msasByState || {};

  const updateMutation = useMutation({
    mutationFn: (data: any) => apiRequest("PATCH", "/api/broker-portal/me", data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/broker-portal/me"] });
      setSaved(true);
      setTimeout(() => { setSaved(false); onClose(); }, 1200);
    },
  });

  const toggleState = (s: string) => {
    const isSelected = targetStates.includes(s);
    if (isSelected) {
      setTargetStates(prev => prev.filter(x => x !== s));
      const stateMsas = msasByState[s] || [];
      setTargetMsas(prev => prev.filter(m => !stateMsas.includes(m)));
      setExpandedStates(prev => prev.filter(x => x !== s));
    } else {
      setTargetStates(prev => [...prev, s]);
      setExpandedStates(prev => prev.includes(s) ? prev : [...prev, s]);
    }
  };

  const toggleMsa = (msa: string) =>
    setTargetMsas(prev => prev.includes(msa) ? prev.filter(m => m !== msa) : [...prev, msa]);

  const addMsa = () => {
    const v = msaInput.trim();
    if (v && !targetMsas.includes(v)) { setTargetMsas([...targetMsas, v]); setMsaInput(""); }
  };

  const addCity = () => {
    const v = cityInput.trim();
    if (v && !targetCities.includes(v)) { setTargetCities([...targetCities, v]); setCityInput(""); }
  };

  const handleSave = () => {
    updateMutation.mutate({ firstName, lastName, phone, brokerage, targetStates, targetMsas, targetCities });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg max-h-[92vh] overflow-y-auto">
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200 sticky top-0 bg-white rounded-t-2xl z-10">
          <h2 className="font-bold text-[#0d2d4e] text-base">Edit Profile & Criteria</h2>
          <button onClick={onClose} className="p-1.5 rounded hover:bg-gray-100 text-gray-400 hover:text-gray-600 transition-colors">
            <X className="w-4 h-4" />
          </button>
        </div>

        <div className="px-6 py-5 space-y-6">
          {/* Contact Info */}
          <div>
            <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">Contact Info</h3>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1">
                <Label className="text-xs">First Name</Label>
                <Input value={firstName} onChange={e => setFirstName(e.target.value)} className="h-9 text-sm" />
              </div>
              <div className="space-y-1">
                <Label className="text-xs">Last Name</Label>
                <Input value={lastName} onChange={e => setLastName(e.target.value)} className="h-9 text-sm" />
              </div>
            </div>
            <div className="grid grid-cols-2 gap-3 mt-3">
              <div className="space-y-1">
                <Label className="text-xs">Phone</Label>
                <Input value={phone} onChange={e => setPhone(e.target.value)} placeholder="(555) 123-4567" className="h-9 text-sm" />
              </div>
              <div className="space-y-1">
                <Label className="text-xs">Brokerage</Label>
                <Input value={brokerage} onChange={e => setBrokerage(e.target.value)} placeholder="ABC Realty" className="h-9 text-sm" />
              </div>
            </div>
          </div>

          {/* Target States */}
          <div>
            <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">Target States</h3>
            <div className="flex flex-wrap gap-1.5">
              {US_STATES.map(s => (
                <button
                  key={s}
                  onClick={() => toggleState(s)}
                  className={`text-xs px-2.5 py-1 rounded-full border font-medium transition-colors ${
                    targetStates.includes(s)
                      ? "bg-[#0d2d4e] text-white border-[#0d2d4e]"
                      : "bg-white text-gray-600 border-gray-200 hover:border-[#0d2d4e]/50"
                  }`}
                >
                  {s}
                </button>
              ))}
            </div>
          </div>

          {/* Target MSAs */}
          <div>
            <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">Target MSA Markets</h3>
            <div className="flex gap-2 mb-2">
              <Input
                value={msaInput}
                onChange={e => setMsaInput(e.target.value)}
                onKeyDown={e => e.key === "Enter" && (e.preventDefault(), addMsa())}
                placeholder="e.g. Charlotte-Concord MSA"
                className="h-9 text-sm flex-1"
              />
              <Button type="button" onClick={addMsa} size="sm" variant="outline" className="h-9">
                <Plus className="w-3.5 h-3.5" />
              </Button>
            </div>
            <div className="flex flex-wrap gap-1.5">
              {targetMsas.map(m => (
                <span key={m} className="inline-flex items-center gap-1 text-xs bg-blue-50 text-blue-700 px-2.5 py-1 rounded-full font-medium">
                  {m}
                  <button onClick={() => setTargetMsas(prev => prev.filter(x => x !== m))} className="hover:text-blue-900 ml-0.5">
                    <X className="w-3 h-3" />
                  </button>
                </span>
              ))}
              {targetMsas.length === 0 && <span className="text-xs text-gray-400">No MSAs added yet</span>}
            </div>
          </div>

          {/* Target Cities */}
          <div>
            <h3 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">Target Cities</h3>
            <div className="flex gap-2 mb-2">
              <Input
                value={cityInput}
                onChange={e => setCityInput(e.target.value)}
                onKeyDown={e => e.key === "Enter" && (e.preventDefault(), addCity())}
                placeholder="e.g. Charlotte, Raleigh"
                className="h-9 text-sm flex-1"
              />
              <Button type="button" onClick={addCity} size="sm" variant="outline" className="h-9">
                <Plus className="w-3.5 h-3.5" />
              </Button>
            </div>
            <div className="flex flex-wrap gap-1.5">
              {targetCities.map(c => (
                <span key={c} className="inline-flex items-center gap-1 text-xs bg-purple-50 text-purple-700 px-2.5 py-1 rounded-full font-medium">
                  {c}
                  <button onClick={() => setTargetCities(prev => prev.filter(x => x !== c))} className="hover:text-purple-900 ml-0.5">
                    <X className="w-3 h-3" />
                  </button>
                </span>
              ))}
              {targetCities.length === 0 && <span className="text-xs text-gray-400">No cities added yet</span>}
            </div>
          </div>
        </div>

        <div className="px-6 pb-6 flex gap-3 sticky bottom-0 bg-white border-t border-gray-100 pt-4">
          <Button
            onClick={handleSave}
            disabled={updateMutation.isPending || saved}
            className="flex-1 bg-[#0d2d4e] hover:bg-[#0d2d4e]/90 text-white h-10"
          >
            {saved ? (
              <span className="flex items-center gap-2"><CheckCircle className="w-4 h-4" /> Saved!</span>
            ) : updateMutation.isPending ? "Saving…" : "Save Changes"}
          </Button>
          <Button variant="outline" onClick={onClose} className="h-10">Cancel</Button>
        </div>
      </div>
    </div>
  );
}

function LoginView({ onLogin }: { onLogin: () => void }) {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  const loginMutation = useMutation({
    mutationFn: (creds: { email: string; password: string }) =>
      apiRequest("POST", "/api/broker-portal/login", creds),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/broker-portal/me"] });
      onLogin();
    },
    onError: async (err: any) => {
      setError(err?.message || "Login failed");
    },
  });

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#081729] to-[#0d2d4e] flex flex-col">
      <div className="flex items-center justify-between px-6 py-4">
        <a href="/" className="flex items-center gap-2">
          <div className="overflow-hidden flex-shrink-0" style={{ width: 36, height: 26 }}>
            <img src={landlinqLogo} alt="" style={{ height: 26, width: "auto", maxWidth: "none" }} />
          </div>
          <span className="text-white font-bold text-base tracking-tight">LandLinq</span>
        </a>
      </div>

      <div className="flex-1 flex items-center justify-center p-4">
        <div className="w-full max-w-sm">
          <div className="text-center mb-8">
            <h1 className="text-2xl font-bold text-white mb-2">Partner Broker Portal</h1>
            <p className="text-[#94a3b8] text-sm">Sign in to view deals in your markets</p>
          </div>

          <div className="bg-white rounded-2xl shadow-2xl p-7">
            <form onSubmit={e => { e.preventDefault(); setError(""); loginMutation.mutate({ email, password }); }} className="space-y-4">
              <div>
                <label className="block text-xs font-semibold text-gray-600 mb-1.5">Email</label>
                <Input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="your@email.com" required className="h-10" autoFocus />
              </div>
              <div>
                <label className="block text-xs font-semibold text-gray-600 mb-1.5">Password</label>
                <Input type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••" required className="h-10" />
              </div>
              {error && (
                <div className="bg-red-50 border border-red-200 rounded-lg px-3 py-2 text-xs text-red-700">{error}</div>
              )}
              <Button type="submit" disabled={loginMutation.isPending} className="w-full h-10 bg-[#0d2d4e] hover:bg-[#0d2d4e]/90 text-white font-semibold">
                {loginMutation.isPending ? "Signing in…" : "Sign In"}
              </Button>
            </form>
            <p className="text-center text-xs text-gray-400 mt-5">
              Don't have an account?{" "}
              <a href="/broker-network" className="text-[#0d2d4e] font-semibold hover:underline">Apply to join</a>
            </p>
          </div>
          <p className="text-center text-xs text-[#64748b] mt-6">
            <a href="/" className="text-[#94a3b8] hover:text-white">← Back to LandLinq</a>
          </p>
        </div>
      </div>
    </div>
  );
}

function PortalView({ account }: { account: BrokerAccount }) {
  const [search, setSearch] = useState("");
  const [selectedDeal, setSelectedDeal] = useState<Deal | null>(null);
  const [stateFilter, setStateFilter] = useState("all");
  const [typeFilter, setTypeFilter] = useState("all");
  const [productTypeFilter, setProductTypeFilter] = useState("all");
  const [sortBy, setSortBy] = useState("newest");
  const [showProfile, setShowProfile] = useState(false);

  const logoutMutation = useMutation({
    mutationFn: () => apiRequest("POST", "/api/broker-portal/logout"),
    onSuccess: () => {
      window.location.href = "/broker-portal";
    },
  });

  const { data: deals = [], isLoading, error: dealsError } = useQuery<Deal[]>({
    queryKey: ["/api/broker-portal/deals"],
    retry: 1,
    staleTime: 0,
  });

  const uniqueStates = Array.from(new Set(deals.map(d => d.state).filter(Boolean))) as string[];

  const uniqueProductTypes = Array.from(new Set(
    deals.flatMap(d => {
      const arr: string[] = Array.isArray(d.product_types)
        ? d.product_types
        : (typeof d.product_types === "string" ? (() => { try { return JSON.parse(d.product_types!); } catch { return []; } })() : []);
      return arr;
    })
  )).sort() as string[];

  const filtered = deals
    .filter(d => {
      const q = search.toLowerCase();
      const matchesSearch = !q || (
        (d.address || "").toLowerCase().includes(q) ||
        (d.city || "").toLowerCase().includes(q) ||
        (d.state || "").toLowerCase().includes(q) ||
        (d.property_name || "").toLowerCase().includes(q)
      );
      const matchesState = stateFilter === "all" || d.state === stateFilter;
      const matchesType = typeFilter === "all" || (d.deal_type || "").toLowerCase() === typeFilter;
      const matchesProductType = productTypeFilter === "all" || (() => {
        const arr: string[] = Array.isArray(d.product_types)
          ? d.product_types
          : (typeof d.product_types === "string" ? (() => { try { return JSON.parse(d.product_types!); } catch { return []; } })() : []);
        return arr.includes(productTypeFilter);
      })();
      return matchesSearch && matchesState && matchesType && matchesProductType;
    })
    .sort((a, b) => {
      if (sortBy === "yoc_desc") {
        const aYoc = parseYoc(a.yield_on_cost);
        const bYoc = parseYoc(b.yield_on_cost);
        const aNum = aYoc ? parseFloat(aYoc) : -Infinity;
        const bNum = bYoc ? parseFloat(bYoc) : -Infinity;
        return bNum - aNum;
      }
      if (sortBy === "rent_desc") {
        const aRent = a.top_rent_psf ? parseFloat(a.top_rent_psf) : -Infinity;
        const bRent = b.top_rent_psf ? parseFloat(b.top_rent_psf) : -Infinity;
        return bRent - aRent;
      }
      if (sortBy === "price_asc") {
        const aP = a.asking_price ? parseInt(a.asking_price) : Infinity;
        const bP = b.asking_price ? parseInt(b.asking_price) : Infinity;
        return aP - bP;
      }
      if (sortBy === "price_desc") {
        const aP = a.asking_price ? parseInt(a.asking_price) : -Infinity;
        const bP = b.asking_price ? parseInt(b.asking_price) : -Infinity;
        return bP - aP;
      }
      if (sortBy === "acres_desc") {
        const aA = a.size_acres ? parseFloat(a.size_acres) : -Infinity;
        const bA = b.size_acres ? parseFloat(b.size_acres) : -Infinity;
        return bA - aA;
      }
      if (sortBy === "units_desc") {
        const aU = a.unit_count || -Infinity;
        const bU = b.unit_count || -Infinity;
        return (bU as number) - (aU as number);
      }
      // newest (default)
      return new Date(b.created_at).getTime() - new Date(a.created_at).getTime();
    });

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Header — matches main site style */}
      <header className="bg-[#081729] text-white sticky top-0 z-40 shadow-md">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3 flex items-center justify-between gap-4">
          {/* Logo */}
          <a href="/" className="flex items-center gap-2 shrink-0">
            <div className="overflow-hidden flex-shrink-0" style={{ width: 36, height: 26 }}>
              <img src={landlinqLogo} alt="" style={{ height: 26, width: "auto", maxWidth: "none" }} />
            </div>
            <span className="font-bold text-base tracking-tight leading-none">LandLinq</span>
            <span className="hidden sm:inline text-[#94a3b8] text-xs ml-1 font-normal">· Partner Broker Portal</span>
          </a>

          {/* Right side */}
          <div className="flex items-center gap-3">
            <button
              onClick={() => setShowProfile(true)}
              className="hidden sm:flex items-center gap-1.5 text-xs text-[#94a3b8] hover:text-white transition-colors px-3 py-1.5 rounded-lg hover:bg-white/10"
            >
              <Settings className="w-3.5 h-3.5" />
              Edit Profile
            </button>
            <div className="hidden sm:block text-right">
              <div className="text-sm font-medium">{account.firstName} {account.lastName}</div>
              {account.brokerage && <div className="text-[11px] text-[#94a3b8]">{account.brokerage}</div>}
            </div>
            <button
              onClick={() => logoutMutation.mutate()}
              className="flex items-center gap-1.5 text-xs text-[#94a3b8] hover:text-white transition-colors px-3 py-1.5 rounded-lg hover:bg-white/10"
            >
              <LogOut className="w-3.5 h-3.5" /> Sign Out
            </button>
          </div>
        </div>
      </header>

      {/* Market summary bar */}
      {(account.targetStates.length > 0 || account.targetMsas.length > 0 || account.targetCities.length > 0) && (
        <div className="bg-white border-b border-gray-200">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-2.5 flex items-center gap-2 flex-wrap">
            <span className="text-xs text-gray-500 font-medium shrink-0">Your Markets:</span>
            {account.targetStates.map(s => (
              <span key={s} className="text-[10px] bg-[#0d2d4e]/10 text-[#0d2d4e] px-2 py-0.5 rounded-full font-medium">{s}</span>
            ))}
            {account.targetMsas.map(m => (
              <span key={m} className="text-[10px] bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full font-medium">{m}</span>
            ))}
            {account.targetCities.map(c => (
              <span key={c} className="text-[10px] bg-purple-100 text-purple-700 px-2 py-0.5 rounded-full font-medium">{c}</span>
            ))}
            <button
              onClick={() => setShowProfile(true)}
              className="text-[10px] text-[#0d2d4e] hover:underline font-medium ml-1"
            >
              Edit →
            </button>
          </div>
        </div>
      )}

      {/* Main content */}
      <div className="flex-1 max-w-7xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-6">
        <div className="flex items-center justify-between gap-4 mb-5 flex-wrap">
          <div>
            <h1 className="text-xl font-bold text-[#0d2d4e]">Available Deals</h1>
            <p className="text-sm text-gray-500 mt-0.5">{filtered.length} deal{filtered.length !== 1 ? "s" : ""} in your markets</p>
          </div>
          <div className="flex items-center gap-2 flex-wrap">
            <button
              onClick={() => setShowProfile(true)}
              className="sm:hidden flex items-center gap-1.5 text-xs border border-gray-200 rounded-lg px-3 py-1.5 text-gray-600 hover:bg-gray-50"
            >
              <Pencil className="w-3.5 h-3.5" /> Edit Profile
            </button>
            {/* Deal type toggle */}
            <div className="flex items-center rounded-lg border border-gray-200 bg-white overflow-hidden">
              {[
                { value: "all",         label: "All Types" },
                { value: "land",        label: "Land" },
                { value: "acquisition", label: "Acquisition" },
              ].map(opt => (
                <button
                  key={opt.value}
                  onClick={() => setTypeFilter(opt.value)}
                  className={`text-xs px-3 py-1.5 font-medium transition-colors border-r last:border-r-0 border-gray-200 ${
                    typeFilter === opt.value
                      ? "bg-[#0d2d4e] text-white"
                      : "text-gray-600 hover:bg-gray-50"
                  }`}
                >
                  {opt.label}
                </button>
              ))}
            </div>
            {uniqueStates.length > 1 && (
              <select
                value={stateFilter}
                onChange={e => setStateFilter(e.target.value)}
                className="text-sm border border-gray-200 rounded-lg px-3 py-1.5 bg-white focus:outline-none focus:ring-2 focus:ring-[#0d2d4e]/20"
              >
                <option value="all">All States</option>
                {uniqueStates.sort().map(s => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
            )}
            {uniqueProductTypes.length > 0 && (
              <select
                value={productTypeFilter}
                onChange={e => setProductTypeFilter(e.target.value)}
                className="text-sm border border-gray-200 rounded-lg px-3 py-1.5 bg-white focus:outline-none focus:ring-2 focus:ring-[#0d2d4e]/20"
              >
                <option value="all">All Product Types</option>
                {uniqueProductTypes.map(t => (
                  <option key={t} value={t}>{formatProductType(t)}</option>
                ))}
              </select>
            )}
            <select
              value={sortBy}
              onChange={e => setSortBy(e.target.value)}
              className="text-sm border border-gray-200 rounded-lg px-3 py-1.5 bg-white focus:outline-none focus:ring-2 focus:ring-[#0d2d4e]/20"
            >
              <option value="newest">Newest First</option>
              <option value="yoc_desc">Highest YOC</option>
              <option value="rent_desc">Highest Mkt Rent</option>
              <option value="price_asc">Price: Low → High</option>
              <option value="price_desc">Price: High → Low</option>
              <option value="acres_desc">Largest Acreage</option>
              <option value="units_desc">Most Units</option>
            </select>
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400" />
              <Input
                value={search}
                onChange={e => setSearch(e.target.value)}
                placeholder="Search deals…"
                className="pl-9 h-9 text-sm w-44"
              />
            </div>
          </div>
        </div>

        {isLoading ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {[1,2,3,4,5,6].map(i => (
              <div key={i} className="bg-white border border-gray-200 rounded-xl p-5 animate-pulse">
                <div className="h-3 bg-gray-200 rounded w-1/3 mb-3" />
                <div className="h-4 bg-gray-200 rounded w-3/4 mb-2" />
                <div className="h-3 bg-gray-200 rounded w-1/2" />
              </div>
            ))}
          </div>
        ) : dealsError ? (
          <div className="text-center py-20">
            <Building2 className="w-12 h-12 mx-auto mb-3 text-red-300" />
            <p className="font-medium text-red-600 mb-1">Unable to load deals</p>
            <p className="text-sm text-gray-500">{String((dealsError as any)?.message || dealsError)}</p>
          </div>
        ) : filtered.length === 0 ? (
          <div className="text-center py-20 text-gray-400">
            <Building2 className="w-12 h-12 mx-auto mb-3 text-gray-200" />
            <p className="font-medium text-gray-500 mb-1">No deals found</p>
            <p className="text-sm">
              {deals.length === 0
                ? "No deals are currently available in your markets."
                : "Try adjusting your search or filter."}
            </p>
            {deals.length === 0 && (
              <button onClick={() => setShowProfile(true)} className="mt-4 text-sm text-[#0d2d4e] underline">
                Update your market criteria
              </button>
            )}
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {filtered.map(deal => (
              <DealCard key={deal.id} deal={deal} onClick={() => setSelectedDeal(deal)} />
            ))}
          </div>
        )}
      </div>

      <Footer />

      {selectedDeal && <DealDetailModal deal={selectedDeal} onClose={() => setSelectedDeal(null)} />}
      {showProfile && <ProfileModal account={account} onClose={() => setShowProfile(false)} />}
    </div>
  );
}

export default function BrokerPortal() {
  const [loggedIn, setLoggedIn] = useState(false);

  const { data: account, isLoading } = useQuery<BrokerAccount>({
    queryKey: ["/api/broker-portal/me"],
    retry: false,
  });

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-[#081729] to-[#0d2d4e] flex items-center justify-center">
        <div className="text-white text-sm">Loading…</div>
      </div>
    );
  }

  if (!account) {
    return <LoginView onLogin={() => setLoggedIn(true)} />;
  }

  return <PortalView account={account} />;
}
